import { mock, spyOn } from "bun:test";
import { rmSync } from "node:fs";
import { Effect, Schema } from "effect";
import type { PartialDeep } from "type-fest";
import type { ShellResult } from "../build/builder.js";
import { Outcome } from "../outcomes/Outcome.js";
import type { OutcomeTelemetry } from "../outcomes/Outcome.js";
import type {
	BaseState,
	CommandDefinition,
	CommandHandler,
	CommandOutput,
	PipelineHandler,
	PluginConfig,
	PluginState,
} from "../plugin/config.js";
import type { HookAction } from "../schemas/pipeline-outputs.js";
import type { AnyPipelineOutput } from "../types/pipeline.js";
import { isPipelineOutput } from "../types/pipeline.js";
import type { BufferShellResult } from "./mocks.js";

// =============================================================================
// HOOK INPUT TYPES
// =============================================================================

/**
 * Base fields present in all hook events.
 * These are auto-generated by the test builder.
 * @public
 */
export interface HookInputBase {
	session_id?: string;
	transcript_path?: string;
	cwd?: string;
	permission_mode?: "default" | "plan" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";
}

/**
 * Test input fields for PreToolUse hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface PreToolUseTestInput extends HookInputBase {
	tool_name: string;
	tool_input: Record<string, unknown>;
	tool_use_id?: string;
}

/**
 * Test input fields for PostToolUse hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface PostToolUseTestInput extends HookInputBase {
	tool_name: string;
	tool_input: Record<string, unknown>;
	tool_response: Record<string, unknown>;
	tool_use_id?: string;
}

/**
 * Test input fields for SessionStart hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface SessionStartTestInput extends HookInputBase {
	source: "startup" | "resume" | "clear" | "compact";
}

/**
 * Test input fields for SessionEnd hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface SessionEndTestInput extends HookInputBase {
	reason: "clear" | "logout" | "prompt_input_exit" | "other";
}

/**
 * Test input fields for Stop hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface StopTestInput extends HookInputBase {
	stop_hook_active: boolean;
}

/**
 * Test input fields for SubagentStop hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface SubagentStopTestInput extends HookInputBase {
	stop_hook_active: boolean;
}

/**
 * Test input fields for UserPromptSubmit hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface UserPromptSubmitTestInput extends HookInputBase {
	prompt: string;
}

/**
 * Test input fields for PreCompact hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface PreCompactTestInput extends HookInputBase {
	trigger: "manual" | "auto";
	custom_instructions?: string;
}

/**
 * Test input fields for Notification hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface NotificationTestInput extends HookInputBase {
	message: string;
	notification_type: string;
}

/**
 * Test input fields for PermissionRequest hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface PermissionRequestTestInput extends HookInputBase {
	tool_name: string;
	tool_input: Record<string, unknown>;
	permission_suggestions?: Record<string, unknown>[];
}

// =============================================================================
// RESULT TYPES
// =============================================================================

/**
 * Result from running a hook test.
 * @public
 */
export interface HookTestResult {
	/** Exit code from the hook (0 = success) */
	exitCode: number;
	/** Raw stdout output */
	stdout: string;
	/** Raw stderr output */
	stderr: string;
	/** Parsed JSON response from the hook */
	output: Record<string, unknown>;
	/** Convenience accessor for hook action (allow/deny/block/etc) */
	action?: HookAction | undefined;
	/** Convenience accessor for additionalContext */
	context?: string | undefined;
	/** Convenience accessor for reason */
	reason?: string | undefined;
	/** The Outcome instance if the handler returned one (for instanceof checks) */
	outcome?: Outcome | undefined;
	/** Telemetry data from the outcome */
	telemetry?: OutcomeTelemetry | undefined;
}

/**
 * Result from running a command test.
 * @public
 */
export interface CommandTestResult {
	/** Exit code from the command (0 = success, 1 = issues found, 2 = fatal error) */
	exitCode: number;
	/** Command output (markdown content) */
	stdout: string;
	/** Error output */
	stderr: string;
	/** Captured console.log calls */
	logs: string[];
	/** Captured console.error calls */
	errors: string[];
	/** Optional structured data returned by the command */
	data?: Record<string, unknown> | undefined;
}

// =============================================================================
// MOCK TYPES
// =============================================================================

/**
 * A tracked mock function that records calls and can be configured.
 * Inspired by Jest's mock function API.
 * @public
 */
export interface MockFn<TArgs extends unknown[] = unknown[], TReturn = unknown> {
	/** The mock function to use in tests */
	(...args: TArgs): TReturn;
	/** Array of all calls made to the mock */
	calls: TArgs[];
	/** Array of all return values */
	results: Array<{ type: "return" | "throw"; value: TReturn | Error }>;
	/** Configure the mock to return a specific value */
	mockReturnValue(value: TReturn): MockFn<TArgs, TReturn>;
	/** Configure the mock to return a value only once */
	mockReturnValueOnce(value: TReturn): MockFn<TArgs, TReturn>;
	/** Configure the mock with a custom implementation */
	mockImplementation(fn: (...args: TArgs) => TReturn): MockFn<TArgs, TReturn>;
	/** Configure the mock to throw an error */
	mockRejectedValue(error: Error): MockFn<TArgs, TReturn>;
	/** Clear all recorded calls and results */
	mockClear(): MockFn<TArgs, TReturn>;
	/** Reset the mock to its initial state */
	mockReset(): MockFn<TArgs, TReturn>;
	/** Get the number of times the mock was called */
	readonly callCount: number;
	/** Check if the mock was called */
	readonly called: boolean;
	/** Get the last call arguments */
	readonly lastCall: TArgs | undefined;
}

/**
 * Result from a mock shell command execution.
 * Mimics the structure returned by awaiting Bun.$.
 * @internal
 */
interface MockShellResult {
	exitCode: number;
	stdout: Buffer;
	stderr: Buffer;
}

/**
 * Mock shell promise that mimics Bun.$ return value.
 * Supports chaining methods like .quiet(), .nothrow(), .text(), etc.
 * @internal
 */
interface MockShellPromise extends PromiseLike<MockShellResult> {
	/** Suppress stdout/stderr output (no-op in mock) */
	quiet(): MockShellPromise;
	/** Don't throw on non-zero exit code */
	nothrow(): MockShellPromise;
	/** Set environment variables (no-op in mock) */
	env(env: Record<string, string>): MockShellPromise;
	/** Set working directory (no-op in mock) */
	cwd(path: string): MockShellPromise;
	/** Get stdout as trimmed string */
	text(): Promise<string>;
	/** Parse stdout as JSON */
	json(): Promise<unknown>;
	/** Get stdout as Blob */
	blob(): Promise<Blob>;
	/** Get stdout as array of non-empty lines */
	lines(): Promise<string[]>;
	/** Promise catch handler */
	catch<TResult = never>(
		onrejected?: ((reason: unknown) => TResult | PromiseLike<TResult>) | null,
	): Promise<MockShellResult | TResult>;
	/** Promise finally handler */
	finally(onfinally?: (() => void) | null): Promise<MockShellResult>;
	/** String tag for proper Promise detection */
	readonly [Symbol.toStringTag]: string;
}

/**
 * Configuration for shell mock with sequencing support.
 * @internal
 */
interface ShellMockConfig {
	/** Default result to return */
	default?: ShellResult;
	/** Queue of results to return in sequence */
	sequence: ShellResult[];
	/** Matcher function for pattern matching */
	matcher?: (command: string) => boolean;
}

/**
 * Configuration for buffer shell mock with sequencing support.
 * Used for InMemoryShellExecutor mocking (command arrays, Buffer results).
 * @internal
 */
interface BufferShellMockConfig {
	/** Default result to return */
	default?: BufferShellResult;
	/** Queue of results to return in sequence */
	sequence: BufferShellResult[];
	/** Matcher function for pattern matching against command array */
	matcher?: (cmd: string[]) => boolean;
}

// =============================================================================
// MOCK FUNCTION FACTORY
// =============================================================================

/**
 * Internal state for a mock function.
 * @internal
 */
interface MockFnState<TArgs extends unknown[], TReturn> {
	calls: TArgs[];
	results: Array<{ type: "return" | "throw"; value: TReturn | Error }>;
	defaultReturn?: TReturn | undefined;
	returnQueue: TReturn[];
	implementation?: ((...args: TArgs) => TReturn) | undefined;
	rejectedError?: Error | undefined;
}

/**
 * Create a tracked mock function with Jest-like API.
 *
 * @param initialImpl - Optional initial implementation
 * @returns A MockFn instance
 *
 * @example
 * ```typescript
 * const mockFetch = createMockFn<[string], Response>();
 * mockFetch.mockReturnValue({ ok: true, json: () => ({}) });
 *
 * await someFunction(mockFetch);
 *
 * expect(mockFetch.called).toBe(true);
 * expect(mockFetch.callCount).toBe(1);
 * expect(mockFetch.lastCall).toEqual(["https://api.example.com"]);
 * ```
 *
 * @public
 */
export function createMockFn<TArgs extends unknown[] = unknown[], TReturn = unknown>(
	initialImpl?: (...args: TArgs) => TReturn,
): MockFn<TArgs, TReturn> {
	const state: MockFnState<TArgs, TReturn> = {
		calls: [],
		results: [],
		returnQueue: [],
		implementation: initialImpl,
	};

	// The actual mock function
	const mockFn = ((...args: TArgs): TReturn => {
		state.calls.push(args);

		// Check for rejected error
		if (state.rejectedError) {
			const error = state.rejectedError;
			state.results.push({ type: "throw", value: error });
			throw error;
		}

		// Check for custom implementation
		if (state.implementation) {
			try {
				const result = state.implementation(...args);
				state.results.push({ type: "return", value: result });
				return result;
			} catch (error) {
				state.results.push({ type: "throw", value: error as Error });
				throw error;
			}
		}

		// Check for queued return values
		if (state.returnQueue.length > 0) {
			const result = state.returnQueue.shift() as TReturn;
			state.results.push({ type: "return", value: result });
			return result;
		}

		// Return default value
		const result = state.defaultReturn as TReturn;
		state.results.push({ type: "return", value: result });
		return result;
	}) as MockFn<TArgs, TReturn>;

	// Attach properties
	Object.defineProperty(mockFn, "calls", {
		get: () => state.calls,
		enumerable: true,
	});

	Object.defineProperty(mockFn, "results", {
		get: () => state.results,
		enumerable: true,
	});

	Object.defineProperty(mockFn, "callCount", {
		get: () => state.calls.length,
		enumerable: true,
	});

	Object.defineProperty(mockFn, "called", {
		get: () => state.calls.length > 0,
		enumerable: true,
	});

	Object.defineProperty(mockFn, "lastCall", {
		get: () => (state.calls.length > 0 ? state.calls[state.calls.length - 1] : undefined),
		enumerable: true,
	});

	// Attach methods
	mockFn.mockReturnValue = (value: TReturn): MockFn<TArgs, TReturn> => {
		state.defaultReturn = value;
		return mockFn;
	};

	mockFn.mockReturnValueOnce = (value: TReturn): MockFn<TArgs, TReturn> => {
		state.returnQueue.push(value);
		return mockFn;
	};

	mockFn.mockImplementation = (fn: (...args: TArgs) => TReturn): MockFn<TArgs, TReturn> => {
		state.implementation = fn;
		return mockFn;
	};

	mockFn.mockRejectedValue = (error: Error): MockFn<TArgs, TReturn> => {
		state.rejectedError = error;
		return mockFn;
	};

	mockFn.mockClear = (): MockFn<TArgs, TReturn> => {
		state.calls = [];
		state.results = [];
		return mockFn;
	};

	mockFn.mockReset = (): MockFn<TArgs, TReturn> => {
		state.calls = [];
		state.results = [];
		state.defaultReturn = undefined;
		state.returnQueue = [];
		state.implementation = initialImpl;
		state.rejectedError = undefined;
		return mockFn;
	};

	return mockFn;
}

// =============================================================================
// BUILDER CONFIGURATION
// =============================================================================

/**
 * Internal state for the test builder.
 * @internal
 */
interface BuilderState<TOptions, TState> {
	options?: TOptions;
	state?: TState;
	hookInput?: Record<string, unknown>;
	hookEventName?: string;
	/** Plugin root directory for resolving relative paths */
	pluginRoot?: string;
	/** Project directory (cwd) for tests */
	projectDir?: string;
	/** Whether to use a temp project directory */
	useTempProject?: boolean;
	/** Temp project directory path (created on demand) */
	tempProjectDir?: string;
	/** Files to create in temp project: path -\> content */
	tempProjectFiles: Map<string, string | Uint8Array>;
	shellResponses: Map<string, ShellResult>;
	shellMocks: Map<string, ShellMockConfig>;
	bufferShellResponses: Map<string, BufferShellResult>;
	bufferShellMocks: Map<string, BufferShellMockConfig>;
	envVars: Map<string, string>;
	// Use unknown to allow storing any MockFn<TArgs, TReturn> variant
	mockFunctions: Map<string, unknown>;
}

// =============================================================================
// PLUGIN TEST BUILDER
// =============================================================================

/**
 * Fluent test builder for plugin hooks and commands.
 *
 * @typeParam TOptions - Validated options type from plugin schema
 * @typeParam TState - State type from setup function
 * @typeParam THooks - Hook definitions from plugin config
 * @typeParam TCommands - Command definitions from plugin config
 *
 * @public
 */
export class PluginTester<
	TOptions,
	TState,
	// biome-ignore lint/suspicious/noExplicitAny: Hooks map has optional properties that don't satisfy Record constraint
	THooks extends Record<string, any>,
	// biome-ignore lint/suspicious/noExplicitAny: CommandDefinitionBase allows string | function for pipeline
	TCommands extends Record<string, any>,
> {
	private state: BuilderState<TOptions, TState> = {
		tempProjectFiles: new Map(),
		shellResponses: new Map(),
		shellMocks: new Map(),
		bufferShellResponses: new Map(),
		bufferShellMocks: new Map(),
		envVars: new Map(),
		mockFunctions: new Map(),
	};

	private savedEnv: Map<string, string | undefined> = new Map();
	private stdoutBuffer = "";
	private stderrBuffer = "";
	private isDisposed = false;
	private isBunShellMocked = false;
	// biome-ignore lint/suspicious/noExplicitAny: Bun.$ type is complex tagged template literal
	private originalBunShell: any = null;

	/**
	 * Plugin configuration reference for type inference.
	 * @internal
	 */
	// biome-ignore lint/suspicious/noExplicitAny: Store plugin config for reference
	private readonly pluginConfig: PluginConfig<any, any, any, any>;

	/**
	 * Create a new test builder for a plugin.
	 * @internal - Use `plugin.test()` instead
	 */
	// biome-ignore lint/suspicious/noExplicitAny: Accept any plugin config
	constructor(pluginConfig: PluginConfig<any, any, any, any>) {
		this.pluginConfig = pluginConfig;
	}

	// =========================================================================
	// CONFIGURATION METHODS (Fluent)
	// =========================================================================

	/**
	 * Set the plugin options for this test.
	 *
	 * @remarks
	 * Accepts deeply partial options - only specify fields needed for your test.
	 * Unspecified fields will be undefined unless the plugin schema provides defaults.
	 *
	 * @param options - Partial options object (deeply partial)
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * // Only specify what the test needs
	 * ctx.withOptions({ TIMEOUT_MS: 5000 });
	 *
	 * // Nested objects are also partial
	 * ctx.withOptions({ config: { debug: true } });
	 * ```
	 */
	withOptions(options: PartialDeep<TOptions>): this {
		this.state.options = options as TOptions;
		return this;
	}

	/**
	 * Set the plugin state (from setup function) for this test.
	 *
	 * @remarks
	 * Accepts deeply partial state - only specify fields needed for your test.
	 * This simulates what setup() would return without running actual detection.
	 *
	 * @param state - Partial state object (deeply partial)
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * // Only specify what the test needs
	 * ctx.withState({ packageManager: "bun" });
	 *
	 * // Nested objects are also partial
	 * ctx.withState({ config: { linters: { biome: true } } });
	 * ```
	 */
	withState(state: PartialDeep<TState>): this {
		this.state.state = state as TState;
		return this;
	}

	/**
	 * Set the plugin root directory for resolving relative paths.
	 *
	 * @remarks
	 * This is essential for command testing when commands are defined
	 * with relative paths like `./commands/test.cmd.ts`. The plugin root
	 * is used to resolve these paths to absolute paths.
	 *
	 * @param path - Absolute path to the plugin root directory
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * // Set to the directory containing your plugin config
	 * ctx.withPluginRoot(import.meta.dir);
	 *
	 * // Or resolve from test file location
	 * ctx.withPluginRoot(resolve(import.meta.dir, ".."));
	 * ```
	 */
	withPluginRoot(path: string): this {
		this.state.pluginRoot = path;
		return this;
	}

	/**
	 * Set the project directory (cwd) for tests.
	 *
	 * @remarks
	 * This sets `CLAUDE_PROJECT_DIR` which represents the user's project
	 * directory where Claude Code is running. Useful for testing commands
	 * that operate on project files.
	 *
	 * @param path - Absolute path to the project directory
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * // Use a temp directory for isolated tests
	 * const tempDir = await mkdtemp(join(tmpdir(), "test-"));
	 * ctx.withProjectDir(tempDir);
	 * ```
	 */
	withProjectDir(path: string): this {
		this.state.projectDir = path;
		return this;
	}

	/**
	 * Use a temporary project directory for isolated file system tests.
	 *
	 * @remarks
	 * Creates an isolated temp directory that acts as the project root.
	 * The directory is automatically created before tests run and cleaned
	 * up when `dispose()` is called.
	 *
	 * Use `withFile()` to add files to the temp project before running tests.
	 *
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * const result = await plugin.test()
	 *   .withTempProject()
	 *   .withFile("package.json", JSON.stringify({ name: "test" }))
	 *   .withFile("tsconfig.json", JSON.stringify({ compilerOptions: {} }))
	 *   .withOptions({ DEBUG: "false" })
	 *   .withState({ enabled: true })
	 *   .runCommand("typecheck", {});
	 * ```
	 */
	withTempProject(): this {
		this.state.useTempProject = true;
		return this;
	}

	/**
	 * Add a file to the temp project directory.
	 *
	 * @remarks
	 * Files are created when tests run. Requires `withTempProject()` to be called first.
	 * Directories are created automatically as needed.
	 *
	 * @param relativePath - Path relative to project root (e.g., "src/index.ts")
	 * @param content - File content as string or binary data
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * ctx.withTempProject()
	 *   .withFile("package.json", JSON.stringify({ name: "test", type: "module" }))
	 *   .withFile("src/index.ts", "export const foo = 1;")
	 *   .withFile("tsconfig.json", JSON.stringify({
	 *     compilerOptions: { strict: true }
	 *   }));
	 * ```
	 */
	withFile(relativePath: string, content: string | Uint8Array): this {
		if (!this.state.useTempProject) {
			throw new Error("PluginTester: withTempProject() must be called before withFile()");
		}
		this.state.tempProjectFiles.set(relativePath, content);
		return this;
	}

	/**
	 * Get the temp project directory path.
	 *
	 * @remarks
	 * Returns the path after tests have run (setupMocks creates the directory).
	 * Returns undefined if withTempProject() wasn't called or tests haven't run yet.
	 *
	 * @returns The temp project directory path, or undefined
	 */
	getTempProjectDir(): string | undefined {
		return this.state.tempProjectDir;
	}

	// =========================================================================
	// HOOK INPUT METHODS (Fluent, type-aware)
	// =========================================================================

	/**
	 * Set input for a PreToolUse hook test.
	 *
	 * @param input - PreToolUse-specific input fields
	 * @returns this for chaining
	 */
	withPreToolUseInput(input: PreToolUseTestInput): this {
		this.state.hookEventName = "PreToolUse";
		this.state.hookInput = {
			hook_event_name: "PreToolUse",
			tool_use_id: input.tool_use_id ?? `tool-${crypto.randomUUID()}`,
			...input,
		};
		return this;
	}

	/**
	 * Set input for a PostToolUse hook test.
	 *
	 * @param input - PostToolUse-specific input fields
	 * @returns this for chaining
	 */
	withPostToolUseInput(input: PostToolUseTestInput): this {
		this.state.hookEventName = "PostToolUse";
		this.state.hookInput = {
			hook_event_name: "PostToolUse",
			tool_use_id: input.tool_use_id ?? `tool-${crypto.randomUUID()}`,
			...input,
		};
		return this;
	}

	/**
	 * Set input for a SessionStart hook test.
	 *
	 * @param input - SessionStart-specific input fields
	 * @returns this for chaining
	 */
	withSessionStartInput(input: SessionStartTestInput): this {
		this.state.hookEventName = "SessionStart";
		this.state.hookInput = {
			hook_event_name: "SessionStart",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a SessionEnd hook test.
	 *
	 * @param input - SessionEnd-specific input fields
	 * @returns this for chaining
	 */
	withSessionEndInput(input: SessionEndTestInput): this {
		this.state.hookEventName = "SessionEnd";
		this.state.hookInput = {
			hook_event_name: "SessionEnd",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a Stop hook test.
	 *
	 * @param input - Stop-specific input fields
	 * @returns this for chaining
	 */
	withStopInput(input: StopTestInput): this {
		this.state.hookEventName = "Stop";
		this.state.hookInput = {
			hook_event_name: "Stop",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a SubagentStop hook test.
	 *
	 * @param input - SubagentStop-specific input fields
	 * @returns this for chaining
	 */
	withSubagentStopInput(input: SubagentStopTestInput): this {
		this.state.hookEventName = "SubagentStop";
		this.state.hookInput = {
			hook_event_name: "SubagentStop",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a UserPromptSubmit hook test.
	 *
	 * @param input - UserPromptSubmit-specific input fields
	 * @returns this for chaining
	 */
	withUserPromptSubmitInput(input: UserPromptSubmitTestInput): this {
		this.state.hookEventName = "UserPromptSubmit";
		this.state.hookInput = {
			hook_event_name: "UserPromptSubmit",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a PreCompact hook test.
	 *
	 * @param input - PreCompact-specific input fields
	 * @returns this for chaining
	 */
	withPreCompactInput(input: PreCompactTestInput): this {
		this.state.hookEventName = "PreCompact";
		this.state.hookInput = {
			hook_event_name: "PreCompact",
			custom_instructions: input.custom_instructions ?? "",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a Notification hook test.
	 *
	 * @param input - Notification-specific input fields
	 * @returns this for chaining
	 */
	withNotificationInput(input: NotificationTestInput): this {
		this.state.hookEventName = "Notification";
		this.state.hookInput = {
			hook_event_name: "Notification",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a PermissionRequest hook test.
	 *
	 * @param input - PermissionRequest-specific input fields
	 * @returns this for chaining
	 */
	withPermissionRequestInput(input: PermissionRequestTestInput): this {
		this.state.hookEventName = "PermissionRequest";
		this.state.hookInput = {
			hook_event_name: "PermissionRequest",
			...input,
		};
		return this;
	}

	// =========================================================================
	// SHELL MOCKING (Fluent)
	// =========================================================================

	/**
	 * Add a mock shell response for a command pattern.
	 *
	 * @remarks
	 * Uses substring matching - the pattern must appear anywhere in the command.
	 * For more flexible matching, use `withShellMatching()` (regex) or
	 * `withShellMatcher()` (custom function).
	 *
	 * @param pattern - Command substring to match (uses `command.includes(pattern)`)
	 * @param result - ShellResult to return for matching commands
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * // Matches any command containing "git status"
	 * ctx.withShell("git status", { exitCode: 0, stdout: "clean", stderr: "" });
	 *
	 * // Also matches "git status --short", "cd /foo && git status", etc.
	 * ```
	 */
	withShell(pattern: string, result: ShellResult): this {
		this.state.shellResponses.set(pattern, result);
		return this;
	}

	/**
	 * Add a mock shell response with regex pattern matching.
	 *
	 * @remarks
	 * Use this for complex patterns where substring matching isn't sufficient.
	 * The regex is tested against the full reconstructed command string.
	 *
	 * @param pattern - RegExp to test against command
	 * @param result - ShellResult to return for matching commands
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * // Match "bunx tsc" with any arguments
	 * ctx.withShellMatching(/bunx\s+tsc/, { exitCode: 0, stdout: "", stderr: "" });
	 *
	 * // Match "npm test" or "bun test"
	 * ctx.withShellMatching(/(?:npm|bun)\s+test/, { exitCode: 0, stdout: "pass", stderr: "" });
	 * ```
	 */
	withShellMatching(pattern: RegExp, result: ShellResult): this {
		// Store as a mock with a matcher function
		const patternKey = `__regex__${pattern.source}__${pattern.flags}`;
		this.state.shellMocks.set(patternKey, {
			default: result,
			sequence: [],
			matcher: (command: string) => pattern.test(command),
		});
		return this;
	}

	/**
	 * Add a mock shell response with a custom matcher function.
	 *
	 * @remarks
	 * Use this for complex matching logic that can't be expressed as a
	 * substring or regex. The matcher receives the full command string.
	 *
	 * @param name - Unique name for the matcher (for internal tracking)
	 * @param matcher - Function that returns true if command matches
	 * @param result - ShellResult to return for matching commands
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * // Match commands that start with "npm" or "yarn"
	 * ctx.withShellMatcher(
	 *   "package-manager",
	 *   (cmd) => cmd.startsWith("npm ") || cmd.startsWith("yarn "),
	 *   { exitCode: 0, stdout: "done", stderr: "" }
	 * );
	 *
	 * // Match based on parsed command structure
	 * ctx.withShellMatcher(
	 *   "tsc-with-project",
	 *   (cmd) => cmd.includes("tsc") && cmd.includes("-p"),
	 *   { exitCode: 0, stdout: "", stderr: "" }
	 * );
	 * ```
	 */
	withShellMatcher(name: string, matcher: (command: string) => boolean, result: ShellResult): this {
		this.state.shellMocks.set(`__matcher__${name}`, {
			default: result,
			sequence: [],
			matcher,
		});
		return this;
	}

	// =========================================================================
	// MOCK UTILITIES (Jest-like API)
	// =========================================================================

	/**
	 * Create a tracked mock function.
	 *
	 * @remarks
	 * Creates a mock function that tracks calls, return values, and provides
	 * Jest-like configuration methods. The mock is registered with the test
	 * context and will be cleaned up on dispose().
	 *
	 * @param name - Unique name for the mock (used for cleanup)
	 * @param initialImpl - Optional initial implementation
	 * @returns A MockFn instance
	 *
	 * @example
	 * ```typescript
	 * const fetchMock = ctx.mockFn<[string], Response>("fetch");
	 * fetchMock.mockReturnValue({ ok: true, json: () => ({}) });
	 *
	 * // Use in test...
	 *
	 * expect(fetchMock.called).toBe(true);
	 * expect(fetchMock.callCount).toBe(1);
	 * ```
	 */
	mockFn<TArgs extends unknown[] = unknown[], TReturn = unknown>(
		name: string,
		initialImpl?: (...args: TArgs) => TReturn,
	): MockFn<TArgs, TReturn> {
		const fn = createMockFn<TArgs, TReturn>(initialImpl);
		this.state.mockFunctions.set(name, fn);
		return fn;
	}

	/**
	 * Add a one-time shell mock response for a command pattern.
	 *
	 * @remarks
	 * The result will only be returned once. Subsequent calls to the same
	 * pattern will return the next queued result or the default response.
	 *
	 * @param pattern - Command string or pattern to match
	 * @param result - ShellResult to return once
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * // First call returns success, subsequent calls return error
	 * ctx.mockShellOnce("npm install", { exitCode: 0, stdout: "installed", stderr: "" });
	 * ctx.withShell("npm install", { exitCode: 1, stdout: "", stderr: "failed" });
	 * ```
	 */
	mockShellOnce(pattern: string, result: ShellResult): this {
		const existing = this.state.shellMocks.get(pattern);
		if (existing) {
			existing.sequence.push(result);
		} else {
			this.state.shellMocks.set(pattern, {
				sequence: [result],
			});
		}
		return this;
	}

	/**
	 * Add a sequence of shell mock responses for a command pattern.
	 *
	 * @remarks
	 * Results will be returned in order. After the sequence is exhausted,
	 * subsequent calls return the default shell response if set.
	 *
	 * @param pattern - Command string or pattern to match
	 * @param results - Array of ShellResults to return in sequence
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * // Simulate retry behavior
	 * ctx.mockShellSequence("curl https://api.example.com", [
	 *   { exitCode: 1, stdout: "", stderr: "timeout" },
	 *   { exitCode: 1, stdout: "", stderr: "timeout" },
	 *   { exitCode: 0, stdout: '{"success": true}', stderr: "" },
	 * ]);
	 * ```
	 */
	mockShellSequence(pattern: string, results: ShellResult[]): this {
		const existing = this.state.shellMocks.get(pattern);
		if (existing) {
			existing.sequence.push(...results);
		} else {
			this.state.shellMocks.set(pattern, {
				sequence: [...results],
			});
		}
		return this;
	}

	/**
	 * Get a shell mock result for a command, consuming from sequence if available.
	 *
	 * @param command - The command being executed
	 * @returns ShellResult or undefined if no mock matches
	 *
	 * @internal
	 */
	getShellMock(command: string): ShellResult | undefined {
		// First check sequenced mocks
		for (const [pattern, config] of this.state.shellMocks) {
			const matches = config.matcher ? config.matcher(command) : command.includes(pattern);
			if (matches) {
				// Return from sequence if available
				if (config.sequence.length > 0) {
					return config.sequence.shift();
				}
				// Return default if set
				if (config.default) {
					return config.default;
				}
			}
		}

		// Fall back to static shell responses
		for (const [pattern, result] of this.state.shellResponses) {
			if (command.includes(pattern)) {
				return result;
			}
		}

		return undefined;
	}

	/**
	 * Clear all call history from registered mock functions.
	 *
	 * @remarks
	 * This clears the calls and results arrays but preserves configured
	 * return values and implementations. Useful between test assertions.
	 *
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * // After first test phase
	 * expect(myMock.callCount).toBe(3);
	 *
	 * ctx.clearMockCalls();
	 *
	 * // Start fresh for next phase
	 * expect(myMock.callCount).toBe(0);
	 * ```
	 */
	clearMockCalls(): this {
		for (const fn of this.state.mockFunctions.values()) {
			(fn as MockFn).mockClear();
		}
		return this;
	}

	/**
	 * Reset all registered mock functions to their initial state.
	 *
	 * @remarks
	 * This clears calls, results, and all configured return values/implementations.
	 *
	 * @returns this for chaining
	 */
	resetMocks(): this {
		for (const fn of this.state.mockFunctions.values()) {
			(fn as MockFn).mockReset();
		}
		// Also reset shell mocks sequences
		for (const config of this.state.shellMocks.values()) {
			config.sequence = [];
		}
		for (const config of this.state.bufferShellMocks.values()) {
			config.sequence = [];
		}
		return this;
	}

	// =========================================================================
	// BUFFER SHELL MOCKING (For InMemoryShellExecutor)
	// =========================================================================

	/**
	 * Add a mock buffer shell response for a command pattern.
	 *
	 * @remarks
	 * Buffer shell mocks are for InMemoryShellExecutor which takes command
	 * arrays and returns BufferShellResult with Buffer stdout/stderr.
	 *
	 * @param pattern - Command string pattern to match (matched against joined command array)
	 * @param result - BufferShellResult to return for matching commands
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * ctx.withBufferShell("git status", {
	 *   exitCode: 0,
	 *   stdout: Buffer.from("clean"),
	 *   stderr: Buffer.from(""),
	 * });
	 * ```
	 */
	withBufferShell(pattern: string, result: BufferShellResult): this {
		this.state.bufferShellResponses.set(pattern, result);
		return this;
	}

	/**
	 * Add a one-time buffer shell mock response for a command pattern.
	 *
	 * @remarks
	 * The result will only be returned once. Subsequent calls to the same
	 * pattern will return the next queued result or the default response.
	 *
	 * @param pattern - Command string pattern to match
	 * @param result - BufferShellResult to return once
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * ctx.mockBufferShellOnce("npm install", {
	 *   exitCode: 0,
	 *   stdout: Buffer.from("installed"),
	 *   stderr: Buffer.from(""),
	 * });
	 * ```
	 */
	mockBufferShellOnce(pattern: string, result: BufferShellResult): this {
		const existing = this.state.bufferShellMocks.get(pattern);
		if (existing) {
			existing.sequence.push(result);
		} else {
			this.state.bufferShellMocks.set(pattern, {
				sequence: [result],
			});
		}
		return this;
	}

	/**
	 * Add a sequence of buffer shell mock responses for a command pattern.
	 *
	 * @remarks
	 * Results will be returned in order. After the sequence is exhausted,
	 * subsequent calls return the default buffer shell response if set.
	 *
	 * @param pattern - Command string pattern to match
	 * @param results - Array of BufferShellResults to return in sequence
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * ctx.mockBufferShellSequence("curl https://api.example.com", [
	 *   { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("timeout") },
	 *   { exitCode: 0, stdout: Buffer.from('{"ok":true}'), stderr: Buffer.from("") },
	 * ]);
	 * ```
	 */
	mockBufferShellSequence(pattern: string, results: BufferShellResult[]): this {
		const existing = this.state.bufferShellMocks.get(pattern);
		if (existing) {
			existing.sequence.push(...results);
		} else {
			this.state.bufferShellMocks.set(pattern, {
				sequence: [...results],
			});
		}
		return this;
	}

	/**
	 * Get a buffer shell mock result for a command, consuming from sequence if available.
	 *
	 * @param cmd - The command array being executed
	 * @returns BufferShellResult or undefined if no mock matches
	 *
	 * @internal
	 */
	getBufferShellMock(cmd: string[]): BufferShellResult | undefined {
		const command = cmd.join(" ");

		// First check sequenced mocks
		for (const [pattern, config] of this.state.bufferShellMocks) {
			const matches = config.matcher ? config.matcher(cmd) : command.includes(pattern);
			if (matches) {
				// Return from sequence if available
				if (config.sequence.length > 0) {
					return config.sequence.shift();
				}
				// Return default if set
				if (config.default) {
					return config.default;
				}
			}
		}

		// Fall back to static buffer shell responses
		for (const [pattern, result] of this.state.bufferShellResponses) {
			if (command.includes(pattern)) {
				return result;
			}
		}

		return undefined;
	}

	// =========================================================================
	// BUN.$ INTERCEPTION
	// =========================================================================

	/**
	 * Activate Bun.$ interception to route shell calls through mock configuration.
	 *
	 * @remarks
	 * After calling this method, all `Bun.$` template literal calls will be
	 * intercepted and routed through the configured shell mocks (withShell,
	 * mockShellOnce, mockShellSequence). The original `Bun.$` is restored
	 * when `dispose()` is called.
	 *
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * ctx.withShell("git status", { exitCode: 0, stdout: "clean", stderr: "" })
	 *    .mockBunShell();
	 *
	 * // Now Bun.$ calls are intercepted
	 * const result = await Bun.$`git status`.text();
	 * expect(result).toBe("clean");
	 * ```
	 */
	mockBunShell(): this {
		if (this.isBunShellMocked) {
			return this;
		}

		// Save original Bun.$
		this.originalBunShell = Bun.$;
		this.isBunShellMocked = true;
		const mockShell = (strings: TemplateStringsArray, ...values: unknown[]) => {
			// Reconstruct command from template literal
			let command = strings[0] ?? "";
			for (let i = 0; i < values.length; i++) {
				const value = values[i];
				// Handle arrays (e.g., Bun.$`${["bunx", "tsc"]}`) - join with spaces
				if (Array.isArray(value)) {
					command += value.join(" ");
				}
				// Handle { raw: string } pattern used for interpolation
				else if (typeof value === "object" && value !== null && "raw" in value) {
					command += String((value as { raw: string }).raw);
				} else {
					command += String(value);
				}
				command += strings[i + 1] ?? "";
			}

			return this.createMockShellPromise(command.trim());
		};

		// Replace Bun.$
		// @ts-expect-error - Replacing Bun.$ with mock
		Bun.$ = mockShell;

		return this;
	}

	/**
	 * Restore original Bun.$ if it was mocked.
	 *
	 * @remarks
	 * This is automatically called by `dispose()`, but can be called manually
	 * if you need to restore Bun.$ before the test ends.
	 *
	 * @returns this for chaining
	 */
	restoreBunShell(): this {
		if (this.isBunShellMocked && this.originalBunShell) {
			Bun.$ = this.originalBunShell;
			this.originalBunShell = null;
			this.isBunShellMocked = false;
		}
		return this;
	}

	/**
	 * Create a mock ShellPromise-like object for a command.
	 *
	 * @param command - The shell command string
	 * @returns A mock object that mimics Bun.$ return value
	 *
	 * @internal
	 */
	private createMockShellPromise(command: string): MockShellPromise {
		let shouldThrow = true; // By default, throw on non-zero exit

		// Get mock result or create default "command not found"
		const getMockResult = (): ShellResult => {
			const result = this.getShellMock(command);
			if (result) {
				return result;
			}
			// Default: command not found
			return { exitCode: 127, stdout: "", stderr: `command not found: ${command.split(" ")[0]}` };
		};

		// Create the base result object
		const createResult = () => {
			const mock = getMockResult();
			return {
				exitCode: mock.exitCode,
				stdout: Buffer.from(mock.stdout),
				stderr: Buffer.from(mock.stderr),
			};
		};

		// The mock shell promise object
		const shellPromise: MockShellPromise = {
			// biome-ignore lint/suspicious/noThenProperty: Required to implement PromiseLike interface
			then<TResult1 = MockShellResult, TResult2 = never>(
				onfulfilled?: ((value: MockShellResult) => TResult1 | PromiseLike<TResult1>) | null,
				onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null,
			): Promise<TResult1 | TResult2> {
				const result = createResult();
				if (shouldThrow && result.exitCode !== 0) {
					const error = new Error(`Command failed: ${command}`);
					(error as NodeJS.ErrnoException).code = String(result.exitCode);
					return Promise.reject(error).then(onfulfilled, onrejected);
				}
				return Promise.resolve(result).then(onfulfilled, onrejected);
			},

			catch<TResult = never>(
				onrejected?: ((reason: unknown) => TResult | PromiseLike<TResult>) | null,
			): Promise<MockShellResult | TResult> {
				return Promise.resolve(shellPromise).catch(onrejected);
			},

			finally(onfinally?: (() => void) | null): Promise<MockShellResult> {
				return Promise.resolve(shellPromise).finally(onfinally);
			},

			// Chainable methods that return the same promise
			quiet(): MockShellPromise {
				return shellPromise;
			},

			nothrow(): MockShellPromise {
				shouldThrow = false;
				return shellPromise;
			},

			env(_env: Record<string, string>): MockShellPromise {
				return shellPromise;
			},

			cwd(_path: string): MockShellPromise {
				return shellPromise;
			},

			// Terminal methods that return different promises
			async text(): Promise<string> {
				const result = await shellPromise.nothrow();
				return result.stdout.toString().trim();
			},

			async json(): Promise<unknown> {
				const text = await shellPromise.text();
				return JSON.parse(text);
			},

			async blob(): Promise<Blob> {
				const result = await shellPromise.nothrow();
				return new Blob([result.stdout]);
			},

			async lines(): Promise<string[]> {
				const text = await shellPromise.text();
				return text.split("\n").filter((line) => line.length > 0);
			},

			// Symbol for proper Promise behavior
			[Symbol.toStringTag]: "MockShellPromise",
		};

		return shellPromise;
	}

	// =========================================================================
	// EXECUTION METHODS (Terminal operations)
	// =========================================================================

	/**
	 * Run a hook handler with the configured test context.
	 *
	 * @param hookType - The hook event type (e.g., "PreToolUse")
	 * @param hookName - The specific hook name to run
	 * @returns Promise resolving to the hook test result
	 *
	 * @example
	 * ```typescript
	 * const result = await ctx.runHook("PreToolUse", "security");
	 * expect(result.action).toBe("allow");
	 * ```
	 */
	async runHook<K extends keyof THooks>(hookType: K, hookName: string): Promise<HookTestResult> {
		this.validateState();
		await this.setupMocks();

		try {
			// Find the hook definition
			// biome-ignore lint/suspicious/noExplicitAny: Dynamic hook type access requires runtime type checking
			const hookDefinitions = (this.pluginConfig.hooks as any)[hookType as string];
			if (!hookDefinitions || !Array.isArray(hookDefinitions)) {
				throw new Error(`No hooks defined for type "${String(hookType)}"`);
			}

			// Find the specific hook by name
			const hookDef = hookDefinitions.find((h: { name?: string }) => h.name === hookName);
			if (!hookDef) {
				const availableHooks = hookDefinitions
					.filter((h: { name?: string }) => h.name)
					.map((h: { name?: string }) => h.name)
					.join(", ");
				throw new Error(
					`Hook "${hookName}" not found in "${String(hookType)}". Available: ${availableHooks || "none"}`,
				);
			}

			// Check for passthrough hooks (no pipeline or handler)
			if (!hookDef.pipeline && !hookDef.handler) {
				throw new Error(`Hook "${hookName}" is a passthrough hook and cannot be tested with runHook()`);
			}

			// Resolve the handler
			const handler = await this.resolveHandler(hookDef);
			if (!handler) {
				throw new Error(`Could not resolve handler for hook "${hookName}"`);
			}

			// Build the handler context
			const hookInput = this.buildHookInput(hookType as string);
			const context = this.buildHandlerContext(hookInput);

			// Call the handler - cast context to match handler signature
			// biome-ignore lint/suspicious/noExplicitAny: Handler context types are verified at runtime
			let output = handler(context as any);

			// Handle Effect, Promise, or sync return
			if (Effect.isEffect(output)) {
				output = await Effect.runPromise(output as Effect.Effect<unknown>);
			} else if (output instanceof Promise) {
				output = await output;
			}

			// Build and return the result
			return this.buildHookResultFromOutput(output);
		} catch (error) {
			// Return error result
			return {
				exitCode: 1,
				stdout: this.stdoutBuffer,
				stderr: error instanceof Error ? error.message : String(error),
				output: {},
				action: undefined,
				context: undefined,
				reason: error instanceof Error ? error.message : String(error),
			};
		}
	}

	/**
	 * Run a command handler with the configured test context.
	 *
	 * @param command - The command name to run
	 * @param args - Optional command arguments (raw values, will be validated against schema)
	 * @returns Promise resolving to the command test result
	 *
	 * @example
	 * ```typescript
	 * const result = await ctx.runCommand("lint", { fix: true, path: "src/" });
	 * expect(result.exitCode).toBe(0);
	 * expect(result.stdout).toContain("All checks passed");
	 * ```
	 */
	async runCommand<K extends keyof TCommands>(
		command: K,
		args?: TCommands[K] extends { args?: infer TArgs }
			? TArgs extends Schema.Schema.Any
				? Partial<Schema.Schema.Type<TArgs>>
				: unknown
			: unknown,
	): Promise<CommandTestResult> {
		this.validateState();
		await this.setupMocks();

		const logs: string[] = [];
		const errors: string[] = [];

		const originalLog = console.log;
		const originalError = console.error;

		console.log = mock((...logArgs: unknown[]) => {
			logs.push(logArgs.map(String).join(" "));
		}) as typeof console.log;

		console.error = mock((...logArgs: unknown[]) => {
			errors.push(logArgs.map(String).join(" "));
		}) as typeof console.error;

		try {
			// Find the command definition
			const commands = this.pluginConfig.commands as Record<string, CommandDefinition> | undefined;
			if (!commands) {
				throw new Error("No commands defined in plugin configuration");
			}

			const commandDef = commands[command as string];
			if (!commandDef) {
				const availableCommands = Object.keys(commands).join(", ");
				throw new Error(`Command "${String(command)}" not found. Available: ${availableCommands || "none"}`);
			}

			// Resolve the handler
			const handler = await this.resolveCommandHandler(commandDef);
			if (!handler) {
				throw new Error(`Could not resolve handler for command "${String(command)}"`);
			}

			// Validate args against the command's schema
			const validatedArgs = await this.validateCommandArgs(commandDef, args ?? {});

			// Build the command context
			const context = this.buildCommandContext(validatedArgs);

			// Call the handler
			// biome-ignore lint/suspicious/noExplicitAny: Command context types are verified at runtime
			const output = await handler(context as any);

			// Validate output structure
			this.validateCommandOutput(output, command as string);

			// Return success result
			return {
				exitCode: output.exitCode,
				stdout: output.output,
				stderr: this.stderrBuffer,
				logs,
				errors,
				data: output.data,
			};
		} catch (error) {
			// Return error result
			return {
				exitCode: 2,
				stdout: "",
				stderr: error instanceof Error ? error.message : String(error),
				logs,
				errors,
			};
		} finally {
			console.log = originalLog;
			console.error = originalError;
		}
	}

	// =========================================================================
	// CLEANUP
	// =========================================================================

	/**
	 * Clean up all mocks and restore original state.
	 * Call this in afterEach() to prevent test pollution.
	 *
	 * @example
	 * ```typescript
	 * afterEach(() => ctx.dispose());
	 * ```
	 */
	dispose(): void {
		if (this.isDisposed) return;
		this.isDisposed = true;

		// Restore environment variables
		for (const [key, value] of this.savedEnv) {
			if (value === undefined) {
				delete process.env[key];
				delete Bun.env[key];
			} else {
				process.env[key] = value;
				Bun.env[key] = value;
			}
		}

		// Reset IO mocks
		// @ts-expect-error - accessing mock restore
		if (Bun.stdin.text?.mockRestore) {
			// @ts-expect-error - accessing mock restore
			Bun.stdin.text.mockRestore();
		}
		// @ts-expect-error - accessing mock restore
		if (process.stdout.write?.mockRestore) {
			// @ts-expect-error - accessing mock restore
			process.stdout.write.mockRestore();
		}
		// @ts-expect-error - accessing mock restore
		if (process.stderr.write?.mockRestore) {
			// @ts-expect-error - accessing mock restore
			process.stderr.write.mockRestore();
		}

		// Restore Bun.$ if mocked
		this.restoreBunShell();

		// Clean up temp project directory
		if (this.state.tempProjectDir) {
			try {
				rmSync(this.state.tempProjectDir, { recursive: true, force: true });
			} catch {
				// Ignore cleanup errors
			}
		}

		// Clear state
		this.state = {
			tempProjectFiles: new Map(),
			shellResponses: new Map(),
			shellMocks: new Map(),
			bufferShellResponses: new Map(),
			bufferShellMocks: new Map(),
			envVars: new Map(),
			mockFunctions: new Map(),
		};
		this.savedEnv.clear();
		this.stdoutBuffer = "";
		this.stderrBuffer = "";
	}

	// =========================================================================
	// INTERNAL HELPERS
	// =========================================================================

	/**
	 * Validate that required state has been configured.
	 * @internal
	 */
	private validateState(): void {
		if (!this.state.options) {
			throw new Error("PluginTester: withOptions() must be called before running tests");
		}
		if (!this.state.state) {
			throw new Error("PluginTester: withState() must be called before running tests");
		}
	}

	/**
	 * Set up mocks for the test run.
	 * @internal
	 */
	private async setupMocks(): Promise<void> {
		// Save and set environment variables
		const prefix = this.pluginConfig.prefix;

		// Create temp project directory if requested
		if (this.state.useTempProject && !this.state.tempProjectDir) {
			const { mkdtemp, mkdir } = await import("node:fs/promises");
			const { tmpdir } = await import("node:os");
			const { join, dirname } = await import("node:path");

			// Create temp directory
			this.state.tempProjectDir = await mkdtemp(join(tmpdir(), "plugin-test-"));

			// Write queued files
			for (const [relativePath, content] of this.state.tempProjectFiles) {
				const fullPath = join(this.state.tempProjectDir, relativePath);
				// Ensure parent directory exists
				const parentDir = dirname(fullPath);
				if (parentDir !== this.state.tempProjectDir) {
					await mkdir(parentDir, { recursive: true });
				}
				await Bun.write(fullPath, content);
			}

			// Use temp dir as project dir
			this.state.projectDir = this.state.tempProjectDir;
		}

		// Set up base env vars - use configured paths or defaults
		this.setEnvVar("CLAUDE_SESSION_ID", crypto.randomUUID());
		this.setEnvVar("CLAUDE_PROJECT_DIR", this.state.projectDir ?? "/test/project");
		this.setEnvVar("CLAUDE_PLUGIN_ROOT", this.state.pluginRoot ?? "/test/plugin");
		this.setEnvVar("CLAUDE_ENV_FILE", "/tmp/test-env.sh");

		// Set up options as env vars
		if (this.state.options) {
			for (const [key, value] of Object.entries(this.state.options as Record<string, unknown>)) {
				const envKey = `${prefix}_${key}`;
				this.setEnvVar(envKey, String(value));
			}
		}

		// Set up state as encoded env var
		if (this.state.state) {
			const stateJson = JSON.stringify(this.state.state);
			const stateBase64 = Buffer.from(stateJson).toString("base64");
			this.setEnvVar(`${prefix}_PLUGIN_STATE`, stateBase64);
		}

		// Mock stdout/stderr capture
		spyOn(process.stdout, "write").mockImplementation((chunk: string | Uint8Array) => {
			this.stdoutBuffer += typeof chunk === "string" ? chunk : new TextDecoder().decode(chunk);
			return true;
		});

		spyOn(process.stderr, "write").mockImplementation((chunk: string | Uint8Array) => {
			this.stderrBuffer += typeof chunk === "string" ? chunk : new TextDecoder().decode(chunk);
			return true;
		});
	}

	/**
	 * Set an environment variable, saving the original value.
	 * @internal
	 */
	private setEnvVar(key: string, value: string): void {
		if (!this.savedEnv.has(key)) {
			this.savedEnv.set(key, process.env[key]);
		}
		process.env[key] = value;
		Bun.env[key] = value;
	}

	/**
	 * Build the full hook input object with defaults.
	 * @internal
	 */
	private buildHookInput(hookType: string): Record<string, unknown> {
		const base = {
			session_id: crypto.randomUUID(),
			transcript_path: "/tmp/transcript.json",
			cwd: "/test/project",
			permission_mode: "default" as const,
			hook_event_name: hookType,
		};

		return {
			...base,
			...this.state.hookInput,
		};
	}

	/**
	 * Resolve a handler from a hook definition.
	 * Supports inline functions and file paths.
	 * @internal
	 */
	// biome-ignore lint/suspicious/noExplicitAny: Hook definitions have varied shapes
	private async resolveHandler(hookDef: any): Promise<PipelineHandler<unknown, unknown, TOptions, TState> | null> {
		// Check for inline pipeline function
		if (typeof hookDef.pipeline === "function") {
			return hookDef.pipeline;
		}

		// Check for inline handler function (raw handler)
		if (typeof hookDef.handler === "function") {
			// Wrap raw handler in pipeline interface
			// Raw handlers call event.end() directly, so we need to adapt
			throw new Error(
				"Raw handlers (handler property) are not supported in runHook(). " +
					"Use pipeline handlers or test raw handlers separately.",
			);
		}

		// Check for file path
		if (typeof hookDef.pipeline === "string") {
			return this.importHandler(hookDef.pipeline);
		}

		if (typeof hookDef.handler === "string") {
			throw new Error(
				"Raw handler file paths (handler property) are not supported in runHook(). " +
					"Use pipeline handlers or test raw handlers separately.",
			);
		}

		return null;
	}

	/**
	 * Import a handler from a file path.
	 * @internal
	 */
	private async importHandler(filePath: string): Promise<PipelineHandler<unknown, unknown, TOptions, TState>> {
		// Try to resolve the path
		let resolvedPath = filePath;

		// If it's a relative path, resolve from plugin root (preferred) or cwd
		if (filePath.startsWith("./") || filePath.startsWith("../")) {
			// Use configured plugin root if available, otherwise fall back to cwd
			const baseDir = this.state.pluginRoot ?? process.cwd();
			resolvedPath = `${baseDir}/${filePath}`;
		}

		try {
			// Dynamic import
			const module = await import(resolvedPath);
			const handler = module.default || module;

			if (typeof handler !== "function") {
				throw new Error(`Handler file "${filePath}" does not export a function`);
			}

			return handler;
		} catch (error) {
			if (error instanceof Error && error.message.includes("Cannot find module")) {
				const baseDir = this.state.pluginRoot ?? process.cwd();
				throw new Error(
					`Could not import handler from "${filePath}". ` +
						`Make sure the file exists and the path is correct relative to plugin root (${baseDir}). ` +
						`Use withPluginRoot() to set the plugin directory.`,
				);
			}
			throw error;
		}
	}

	/**
	 * Build the handler context from configured state.
	 * @internal
	 */
	private buildHandlerContext(input: Record<string, unknown>): {
		input: unknown;
		options: TOptions;
		state: PluginState<TState>;
	} {
		// Create base state
		const baseState: BaseState = {
			projectDir: Bun.env.CLAUDE_PROJECT_DIR ?? "/test/project",
			pluginDir: Bun.env.CLAUDE_PLUGIN_ROOT ?? "/test/plugin",
			pluginEnvFile: Bun.env.CLAUDE_ENV_FILE ?? "/tmp/test-env.sh",
		};

		// Merge base state with user-provided state
		const pluginState: PluginState<TState> = {
			...baseState,
			...(this.state.state as TState),
		};

		return {
			input,
			options: this.state.options as TOptions,
			state: pluginState,
		};
	}

	/**
	 * Build a HookTestResult from pipeline output.
	 * @internal
	 */
	private buildHookResultFromOutput(output: unknown): HookTestResult {
		// Check if it's an Outcome instance (new pattern)
		if (Outcome.isOutcome(output)) {
			const response = output.toResponse();
			const telemetry = output.toTelemetry();

			// Extract convenience fields from response
			const action = (response.permissionDecision ?? response.decision ?? undefined) as HookAction | undefined;
			const context = response.additionalContext as string | undefined;
			const reason = response.reason as string | undefined;

			return {
				exitCode: 0,
				stdout: JSON.stringify(response),
				stderr: this.stderrBuffer,
				output: response,
				action,
				context,
				reason,
				outcome: output,
				telemetry,
			};
		}

		// Check if it's a valid pipeline output (legacy pattern)
		if (!isPipelineOutput(output)) {
			return {
				exitCode: 1,
				stdout: "",
				stderr: "Handler returned non-pipeline output",
				output: typeof output === "object" && output !== null ? (output as Record<string, unknown>) : {},
				action: undefined,
				context: undefined,
				reason: "Handler returned non-pipeline output",
			};
		}

		const pipelineOutput = output as AnyPipelineOutput;

		// Extract convenience fields
		let action: HookAction | undefined;
		if ("action" in pipelineOutput) {
			action = pipelineOutput.action;
		}

		let context: string | undefined;
		if ("claudeContext" in pipelineOutput && pipelineOutput.claudeContext) {
			context = pipelineOutput.claudeContext;
		}

		let reason: string | undefined;
		if ("reason" in pipelineOutput && pipelineOutput.reason) {
			reason = pipelineOutput.reason;
		}

		// Determine exit code based on status
		const exitCode = pipelineOutput.status === "error" || pipelineOutput.status === "timeout" ? 1 : 0;

		return {
			exitCode,
			stdout: JSON.stringify(pipelineOutput),
			stderr: this.stderrBuffer,
			output: pipelineOutput as Record<string, unknown>,
			action,
			context,
			reason,
		};
	}

	// =========================================================================
	// COMMAND HELPERS
	// =========================================================================

	/**
	 * Resolve a command handler from a command definition.
	 * Supports inline functions and file paths.
	 * @internal
	 */
	private async resolveCommandHandler(
		commandDef: CommandDefinition,
	): Promise<CommandHandler<unknown, TOptions, TState> | null> {
		// Check for inline pipeline function
		if (typeof commandDef.pipeline === "function") {
			return commandDef.pipeline as CommandHandler<unknown, TOptions, TState>;
		}

		// Check for file path
		if (typeof commandDef.pipeline === "string") {
			return this.importCommandHandler(commandDef.pipeline);
		}

		return null;
	}

	/**
	 * Import a command handler from a file path.
	 * @internal
	 */
	private async importCommandHandler(filePath: string): Promise<CommandHandler<unknown, TOptions, TState>> {
		// Try to resolve the path
		let resolvedPath = filePath;

		// If it's a relative path, resolve from plugin root (preferred) or cwd
		if (filePath.startsWith("./") || filePath.startsWith("../")) {
			// Use configured plugin root if available, otherwise fall back to cwd
			const baseDir = this.state.pluginRoot ?? process.cwd();
			resolvedPath = `${baseDir}/${filePath}`;
		}

		try {
			// Dynamic import
			const module = await import(resolvedPath);
			const handler = module.default || module;

			if (typeof handler !== "function") {
				throw new Error(`Command handler file "${filePath}" does not export a function`);
			}

			return handler;
		} catch (error) {
			if (error instanceof Error && error.message.includes("Cannot find module")) {
				const baseDir = this.state.pluginRoot ?? process.cwd();
				throw new Error(
					`Could not import command handler from "${filePath}". ` +
						`Make sure the file exists and the path is correct relative to plugin root (${baseDir}). ` +
						`Use withPluginRoot() to set the plugin directory.`,
				);
			}
			throw error;
		}
	}

	/**
	 * Validate command arguments against the command's schema.
	 * @internal
	 */
	private async validateCommandArgs(commandDef: CommandDefinition, args: Record<string, unknown>): Promise<unknown> {
		const schema = commandDef.args;

		// If no schema defined, return args as-is (empty object for no-arg commands)
		if (!schema) {
			return args;
		}

		// Cast to Effect Schema for decoding
		const effectSchema = schema as Schema.Schema<unknown>;

		try {
			return Schema.decodeUnknownSync(effectSchema)(args);
		} catch (err) {
			const message = err instanceof Error ? err.message : String(err);
			throw new Error(`Argument validation failed: ${message}`);
		}
	}

	/**
	 * Build the command context from configured state and args.
	 * @internal
	 */
	private buildCommandContext(args: unknown): {
		args: unknown;
		options: TOptions;
		state: PluginState<TState>;
	} {
		// Create base state
		const baseState: BaseState = {
			projectDir: Bun.env.CLAUDE_PROJECT_DIR ?? "/test/project",
			pluginDir: Bun.env.CLAUDE_PLUGIN_ROOT ?? "/test/plugin",
			pluginEnvFile: Bun.env.CLAUDE_ENV_FILE ?? "/tmp/test-env.sh",
		};

		// Merge base state with user-provided state
		const pluginState: PluginState<TState> = {
			...baseState,
			...(this.state.state as TState),
		};

		return {
			args,
			options: this.state.options as TOptions,
			state: pluginState,
		};
	}

	/**
	 * Validate command output structure.
	 * @internal
	 */
	private validateCommandOutput(output: CommandOutput, commandName: string): void {
		if (typeof output.exitCode !== "number") {
			throw new Error(`Command "${commandName}" returned invalid exitCode: ${output.exitCode}`);
		}
		if (typeof output.output !== "string") {
			throw new Error(`Command "${commandName}" returned invalid output: expected string`);
		}
		if (output.exitCode < 0 || output.exitCode > 255) {
			throw new Error(`Command "${commandName}" returned invalid exitCode: must be 0-255`);
		}
	}
}
