[install]
publicHoistPattern = [ 
  "@changesets/cli",
  "@commitlint/cli",
  "@commitlint/config-conventional",
  "@commitlint/cz-commitlint",
  "@rslib/core",
  "@savvy-web/cli",
  "@savvy-web/mcp",
  "@types/bun",
  "@types/node",
  "@types/react",
  "@types/react-dom",
  "@typescript/native-preview",
  "@vitest/coverage-v8",
  "commitizen",
  "husky",
  "lint-staged",
  "markdownlint-cli2",
  "markdownlint-cli2-formatter-codequality",
  "tsx",
  "turbo",
  "typescript",
  "vitest",
  "vitest-agent-reporter"
]