[test]
coverage = true
coverageSkipTestFiles = true  # default false
# To require 90% line-level and function-level coverage
coverageThreshold = { lines = 0.8, functions = 0.8, statements= 0.8, perFile = true }
coveragePathIgnorePatterns = [
	"src/otel/classes/Sidecar.ts",
	"src/otel/sidecar/classes/SidecarServer.ts",
	"src/otel/sidecar/classes/EventHandler.ts",
	"src/otel/sidecar/classes/MetricHandler.ts",
	"src/otel/sidecar/classes/SidecarExporters.ts",
	"src/otel/sidecar/classes/SidecarLog.ts",
	"src/otel/sidecar/classes/SidecarProviders.ts",
	"src/otel/sidecar/classes/SidecarResource.ts",
	"src/otel/sidecar/classes/SidecarRouter.ts",
	"src/otel/sidecar/classes/SpanHandler.ts",
	"src/pipeline/classes/Pipeline.ts",
	"src/cli/index.ts",
	"src/cli/init/scaffold.ts",
	"src/cli/init/index.ts",
	"src/cli/init/detect-defaults.ts",
	"src/testing/builder.ts",
]
coverageReporter  = ["text", "lcov"]
