import { mock, spyOn } from "bun:test";
import type { PartialDeep } from "type-fest";
import type { z } from "zod";
import type { ShellResult } from "../build/builder.js";
import type {
	BaseState,
	CommandDefinition,
	CommandHandler,
	CommandOutput,
	PipelineHandler,
	PluginConfig,
	PluginState,
} from "../pipeline/config.js";
import type { AnyPipelineOutput, HookAction } from "../pipeline/types.js";
import { isPipelineOutput } from "../pipeline/types.js";

// =============================================================================
// HOOK INPUT TYPES
// =============================================================================

/**
 * Base fields present in all hook events.
 * These are auto-generated by the test builder.
 * @public
 */
export interface HookInputBase {
	session_id?: string;
	transcript_path?: string;
	cwd?: string;
	permission_mode?: "default" | "plan" | "acceptEdits" | "bypassPermissions";
}

/**
 * Test input fields for PreToolUse hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface PreToolUseTestInput extends HookInputBase {
	tool_name: string;
	tool_input: Record<string, unknown>;
	tool_use_id?: string;
}

/**
 * Test input fields for PostToolUse hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface PostToolUseTestInput extends HookInputBase {
	tool_name: string;
	tool_input: Record<string, unknown>;
	tool_response: Record<string, unknown>;
	tool_use_id?: string;
}

/**
 * Test input fields for SessionStart hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface SessionStartTestInput extends HookInputBase {
	source: "startup" | "resume" | "clear" | "compact";
}

/**
 * Test input fields for SessionEnd hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface SessionEndTestInput extends HookInputBase {
	reason: "clear" | "logout" | "prompt_input_exit" | "other";
}

/**
 * Test input fields for Stop hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface StopTestInput extends HookInputBase {
	stop_hook_active: boolean;
}

/**
 * Test input fields for SubagentStop hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface SubagentStopTestInput extends HookInputBase {
	stop_hook_active: boolean;
}

/**
 * Test input fields for UserPromptSubmit hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface UserPromptSubmitTestInput extends HookInputBase {
	prompt: string;
}

/**
 * Test input fields for PreCompact hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface PreCompactTestInput extends HookInputBase {
	trigger: "manual" | "auto";
	custom_instructions?: string;
}

/**
 * Test input fields for Notification hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface NotificationTestInput extends HookInputBase {
	message: string;
	notification_type: string;
}

/**
 * Test input fields for PermissionRequest hooks.
 * @remarks Simplified version with optional base fields for testing.
 * @public
 */
export interface PermissionRequestTestInput extends HookInputBase {
	message: string;
	notification_type: string;
}

// =============================================================================
// RESULT TYPES
// =============================================================================

/**
 * Result from running a hook test.
 * @public
 */
export interface HookTestResult {
	/** Exit code from the hook (0 = success) */
	exitCode: number;
	/** Raw stdout output */
	stdout: string;
	/** Raw stderr output */
	stderr: string;
	/** Parsed JSON response from the hook */
	output: Record<string, unknown>;
	/** Convenience accessor for hook action (allow/deny/block/etc) */
	action?: HookAction;
	/** Convenience accessor for additionalContext */
	context?: string;
	/** Convenience accessor for reason */
	reason?: string;
}

/**
 * Result from running a command test.
 * @public
 */
export interface CommandTestResult {
	/** Exit code from the command (0 = success, 1 = issues found, 2 = fatal error) */
	exitCode: number;
	/** Command output (markdown content) */
	stdout: string;
	/** Error output */
	stderr: string;
	/** Captured console.log calls */
	logs: string[];
	/** Captured console.error calls */
	errors: string[];
	/** Optional structured data returned by the command */
	data?: Record<string, unknown>;
}

// =============================================================================
// BUILDER CONFIGURATION
// =============================================================================

/**
 * Internal state for the test builder.
 * @internal
 */
interface BuilderState<TOptions, TState> {
	options?: TOptions;
	state?: TState;
	hookInput?: Record<string, unknown>;
	hookEventName?: string;
	shellResponses: Map<string, ShellResult>;
	envVars: Map<string, string>;
}

// =============================================================================
// PLUGIN TEST BUILDER
// =============================================================================

/**
 * Fluent test builder for plugin hooks and commands.
 *
 * @typeParam TOptions - Validated options type from plugin schema
 * @typeParam TState - State type from setup function
 * @typeParam THooks - Hook definitions from plugin config
 * @typeParam TCommands - Command definitions from plugin config
 *
 * @public
 */
export class PluginTester<
	TOptions,
	TState,
	// biome-ignore lint/suspicious/noExplicitAny: Hooks map has optional properties that don't satisfy Record constraint
	THooks extends Record<string, any>,
	// biome-ignore lint/suspicious/noExplicitAny: CommandDefinitionBase allows string | function for pipeline
	TCommands extends Record<string, any>,
> {
	private state: BuilderState<TOptions, TState> = {
		shellResponses: new Map(),
		envVars: new Map(),
	};

	private savedEnv: Map<string, string | undefined> = new Map();
	private stdoutBuffer = "";
	private stderrBuffer = "";
	private isDisposed = false;

	/**
	 * Plugin configuration reference for type inference.
	 * @internal
	 */
	// biome-ignore lint/suspicious/noExplicitAny: Store plugin config for reference
	private readonly pluginConfig: PluginConfig<any, any, any>;

	/**
	 * Create a new test builder for a plugin.
	 * @internal - Use `plugin.test()` instead
	 */
	// biome-ignore lint/suspicious/noExplicitAny: Accept any plugin config
	constructor(pluginConfig: PluginConfig<any, any, any>) {
		this.pluginConfig = pluginConfig;
	}

	// =========================================================================
	// CONFIGURATION METHODS (Fluent)
	// =========================================================================

	/**
	 * Set the plugin options for this test.
	 *
	 * @remarks
	 * Accepts deeply partial options - only specify fields needed for your test.
	 * Unspecified fields will be undefined unless the plugin schema provides defaults.
	 *
	 * @param options - Partial options object (deeply partial)
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * // Only specify what the test needs
	 * ctx.withOptions({ TIMEOUT_MS: 5000 });
	 *
	 * // Nested objects are also partial
	 * ctx.withOptions({ config: { debug: true } });
	 * ```
	 */
	withOptions(options: PartialDeep<TOptions>): this {
		this.state.options = options as TOptions;
		return this;
	}

	/**
	 * Set the plugin state (from setup function) for this test.
	 *
	 * @remarks
	 * Accepts deeply partial state - only specify fields needed for your test.
	 * This simulates what setup() would return without running actual detection.
	 *
	 * @param state - Partial state object (deeply partial)
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * // Only specify what the test needs
	 * ctx.withState({ packageManager: "bun" });
	 *
	 * // Nested objects are also partial
	 * ctx.withState({ config: { linters: { biome: true } } });
	 * ```
	 */
	withState(state: PartialDeep<TState>): this {
		this.state.state = state as TState;
		return this;
	}

	// =========================================================================
	// HOOK INPUT METHODS (Fluent, type-aware)
	// =========================================================================

	/**
	 * Set input for a PreToolUse hook test.
	 *
	 * @param input - PreToolUse-specific input fields
	 * @returns this for chaining
	 */
	withPreToolUseInput(input: PreToolUseTestInput): this {
		this.state.hookEventName = "PreToolUse";
		this.state.hookInput = {
			hook_event_name: "PreToolUse",
			tool_use_id: input.tool_use_id ?? `tool-${crypto.randomUUID()}`,
			...input,
		};
		return this;
	}

	/**
	 * Set input for a PostToolUse hook test.
	 *
	 * @param input - PostToolUse-specific input fields
	 * @returns this for chaining
	 */
	withPostToolUseInput(input: PostToolUseTestInput): this {
		this.state.hookEventName = "PostToolUse";
		this.state.hookInput = {
			hook_event_name: "PostToolUse",
			tool_use_id: input.tool_use_id ?? `tool-${crypto.randomUUID()}`,
			...input,
		};
		return this;
	}

	/**
	 * Set input for a SessionStart hook test.
	 *
	 * @param input - SessionStart-specific input fields
	 * @returns this for chaining
	 */
	withSessionStartInput(input: SessionStartTestInput): this {
		this.state.hookEventName = "SessionStart";
		this.state.hookInput = {
			hook_event_name: "SessionStart",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a SessionEnd hook test.
	 *
	 * @param input - SessionEnd-specific input fields
	 * @returns this for chaining
	 */
	withSessionEndInput(input: SessionEndTestInput): this {
		this.state.hookEventName = "SessionEnd";
		this.state.hookInput = {
			hook_event_name: "SessionEnd",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a Stop hook test.
	 *
	 * @param input - Stop-specific input fields
	 * @returns this for chaining
	 */
	withStopInput(input: StopTestInput): this {
		this.state.hookEventName = "Stop";
		this.state.hookInput = {
			hook_event_name: "Stop",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a SubagentStop hook test.
	 *
	 * @param input - SubagentStop-specific input fields
	 * @returns this for chaining
	 */
	withSubagentStopInput(input: SubagentStopTestInput): this {
		this.state.hookEventName = "SubagentStop";
		this.state.hookInput = {
			hook_event_name: "SubagentStop",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a UserPromptSubmit hook test.
	 *
	 * @param input - UserPromptSubmit-specific input fields
	 * @returns this for chaining
	 */
	withUserPromptSubmitInput(input: UserPromptSubmitTestInput): this {
		this.state.hookEventName = "UserPromptSubmit";
		this.state.hookInput = {
			hook_event_name: "UserPromptSubmit",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a PreCompact hook test.
	 *
	 * @param input - PreCompact-specific input fields
	 * @returns this for chaining
	 */
	withPreCompactInput(input: PreCompactTestInput): this {
		this.state.hookEventName = "PreCompact";
		this.state.hookInput = {
			hook_event_name: "PreCompact",
			custom_instructions: input.custom_instructions ?? "",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a Notification hook test.
	 *
	 * @param input - Notification-specific input fields
	 * @returns this for chaining
	 */
	withNotificationInput(input: NotificationTestInput): this {
		this.state.hookEventName = "Notification";
		this.state.hookInput = {
			hook_event_name: "Notification",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a PermissionRequest hook test.
	 *
	 * @param input - PermissionRequest-specific input fields
	 * @returns this for chaining
	 */
	withPermissionRequestInput(input: PermissionRequestTestInput): this {
		this.state.hookEventName = "PermissionRequest";
		this.state.hookInput = {
			hook_event_name: "PermissionRequest",
			...input,
		};
		return this;
	}

	// =========================================================================
	// SHELL MOCKING (Fluent)
	// =========================================================================

	/**
	 * Add a mock shell response for a command pattern.
	 *
	 * @param pattern - Command string or pattern to match
	 * @param result - ShellResult to return for matching commands
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * ctx.withShell("git status", { exitCode: 0, stdout: "clean", stderr: "" });
	 * ```
	 */
	withShell(pattern: string, result: ShellResult): this {
		this.state.shellResponses.set(pattern, result);
		return this;
	}

	// =========================================================================
	// EXECUTION METHODS (Terminal operations)
	// =========================================================================

	/**
	 * Run a hook handler with the configured test context.
	 *
	 * @param hookType - The hook event type (e.g., "PreToolUse")
	 * @param hookName - The specific hook name to run
	 * @returns Promise resolving to the hook test result
	 *
	 * @example
	 * ```typescript
	 * const result = await ctx.runHook("PreToolUse", "security");
	 * expect(result.action).toBe("allow");
	 * ```
	 */
	async runHook<K extends keyof THooks>(hookType: K, hookName: string): Promise<HookTestResult> {
		this.validateState();
		this.setupMocks();

		try {
			// Find the hook definition
			// biome-ignore lint/suspicious/noExplicitAny: Dynamic hook type access requires runtime type checking
			const hookDefinitions = (this.pluginConfig.hooks as any)[hookType as string];
			if (!hookDefinitions || !Array.isArray(hookDefinitions)) {
				throw new Error(`No hooks defined for type "${String(hookType)}"`);
			}

			// Find the specific hook by name
			const hookDef = hookDefinitions.find((h: { name?: string }) => h.name === hookName);
			if (!hookDef) {
				const availableHooks = hookDefinitions
					.filter((h: { name?: string }) => h.name)
					.map((h: { name?: string }) => h.name)
					.join(", ");
				throw new Error(
					`Hook "${hookName}" not found in "${String(hookType)}". Available: ${availableHooks || "none"}`,
				);
			}

			// Check for passthrough hooks (no pipeline or handler)
			if (!hookDef.pipeline && !hookDef.handler) {
				throw new Error(`Hook "${hookName}" is a passthrough hook and cannot be tested with runHook()`);
			}

			// Resolve the handler
			const handler = await this.resolveHandler(hookDef);
			if (!handler) {
				throw new Error(`Could not resolve handler for hook "${hookName}"`);
			}

			// Build the handler context
			const hookInput = this.buildHookInput(hookType as string);
			const context = this.buildHandlerContext(hookInput);

			// Call the handler - cast context to match handler signature
			// biome-ignore lint/suspicious/noExplicitAny: Handler context types are verified at runtime
			const output = await handler(context as any);

			// Build and return the result
			return this.buildHookResultFromOutput(output);
		} catch (error) {
			// Return error result
			return {
				exitCode: 1,
				stdout: this.stdoutBuffer,
				stderr: error instanceof Error ? error.message : String(error),
				output: {},
				action: undefined,
				context: undefined,
				reason: error instanceof Error ? error.message : String(error),
			};
		}
	}

	/**
	 * Run a command handler with the configured test context.
	 *
	 * @param command - The command name to run
	 * @param args - Optional command arguments (raw values, will be validated against schema)
	 * @returns Promise resolving to the command test result
	 *
	 * @example
	 * ```typescript
	 * const result = await ctx.runCommand("lint", { fix: true, path: "src/" });
	 * expect(result.exitCode).toBe(0);
	 * expect(result.stdout).toContain("All checks passed");
	 * ```
	 */
	async runCommand<K extends keyof TCommands>(
		command: K,
		args?: TCommands[K] extends { args?: infer TArgs }
			? TArgs extends z.ZodType
				? Partial<z.infer<TArgs>>
				: unknown
			: unknown,
	): Promise<CommandTestResult> {
		this.validateState();
		this.setupMocks();

		const logs: string[] = [];
		const errors: string[] = [];

		const originalLog = console.log;
		const originalError = console.error;

		console.log = mock((...logArgs: unknown[]) => {
			logs.push(logArgs.map(String).join(" "));
		}) as typeof console.log;

		console.error = mock((...logArgs: unknown[]) => {
			errors.push(logArgs.map(String).join(" "));
		}) as typeof console.error;

		try {
			// Find the command definition
			const commands = this.pluginConfig.commands as Record<string, CommandDefinition> | undefined;
			if (!commands) {
				throw new Error("No commands defined in plugin configuration");
			}

			const commandDef = commands[command as string];
			if (!commandDef) {
				const availableCommands = Object.keys(commands).join(", ");
				throw new Error(`Command "${String(command)}" not found. Available: ${availableCommands || "none"}`);
			}

			// Resolve the handler
			const handler = await this.resolveCommandHandler(commandDef);
			if (!handler) {
				throw new Error(`Could not resolve handler for command "${String(command)}"`);
			}

			// Validate args against the command's schema
			const validatedArgs = await this.validateCommandArgs(commandDef, args ?? {});

			// Build the command context
			const context = this.buildCommandContext(validatedArgs);

			// Call the handler
			// biome-ignore lint/suspicious/noExplicitAny: Command context types are verified at runtime
			const output = await handler(context as any);

			// Validate output structure
			this.validateCommandOutput(output, command as string);

			// Return success result
			return {
				exitCode: output.exitCode,
				stdout: output.output,
				stderr: this.stderrBuffer,
				logs,
				errors,
				data: output.data,
			};
		} catch (error) {
			// Return error result
			return {
				exitCode: 2,
				stdout: "",
				stderr: error instanceof Error ? error.message : String(error),
				logs,
				errors,
			};
		} finally {
			console.log = originalLog;
			console.error = originalError;
		}
	}

	// =========================================================================
	// CLEANUP
	// =========================================================================

	/**
	 * Clean up all mocks and restore original state.
	 * Call this in afterEach() to prevent test pollution.
	 *
	 * @example
	 * ```typescript
	 * afterEach(() => ctx.dispose());
	 * ```
	 */
	dispose(): void {
		if (this.isDisposed) return;
		this.isDisposed = true;

		// Restore environment variables
		for (const [key, value] of this.savedEnv) {
			if (value === undefined) {
				delete process.env[key];
				delete Bun.env[key];
			} else {
				process.env[key] = value;
				Bun.env[key] = value;
			}
		}

		// Reset IO mocks
		// @ts-expect-error - accessing mock restore
		if (Bun.stdin.text?.mockRestore) {
			// @ts-expect-error - accessing mock restore
			Bun.stdin.text.mockRestore();
		}
		// @ts-expect-error - accessing mock restore
		if (process.stdout.write?.mockRestore) {
			// @ts-expect-error - accessing mock restore
			process.stdout.write.mockRestore();
		}
		// @ts-expect-error - accessing mock restore
		if (process.stderr.write?.mockRestore) {
			// @ts-expect-error - accessing mock restore
			process.stderr.write.mockRestore();
		}

		// Clear state
		this.state = {
			shellResponses: new Map(),
			envVars: new Map(),
		};
		this.savedEnv.clear();
		this.stdoutBuffer = "";
		this.stderrBuffer = "";
	}

	// =========================================================================
	// INTERNAL HELPERS
	// =========================================================================

	/**
	 * Validate that required state has been configured.
	 * @internal
	 */
	private validateState(): void {
		if (!this.state.options) {
			throw new Error("PluginTester: withOptions() must be called before running tests");
		}
		if (!this.state.state) {
			throw new Error("PluginTester: withState() must be called before running tests");
		}
	}

	/**
	 * Set up mocks for the test run.
	 * @internal
	 */
	private setupMocks(): void {
		// Save and set environment variables
		const prefix = this.pluginConfig.prefix;

		// Set up base env vars
		this.setEnvVar("CLAUDE_SESSION_ID", crypto.randomUUID());
		this.setEnvVar("CLAUDE_PROJECT_DIR", "/test/project");
		this.setEnvVar("CLAUDE_PLUGIN_ROOT", "/test/plugin");
		this.setEnvVar("CLAUDE_ENV_FILE", "/tmp/test-env.sh");

		// Set up options as env vars
		if (this.state.options) {
			for (const [key, value] of Object.entries(this.state.options as Record<string, unknown>)) {
				const envKey = `${prefix}_${key}`;
				this.setEnvVar(envKey, String(value));
			}
		}

		// Set up state as encoded env var
		if (this.state.state) {
			const stateJson = JSON.stringify(this.state.state);
			const stateBase64 = Buffer.from(stateJson).toString("base64");
			this.setEnvVar(`${prefix}_PLUGIN_STATE`, stateBase64);
		}

		// Mock stdout/stderr capture
		spyOn(process.stdout, "write").mockImplementation((chunk: string | Uint8Array) => {
			this.stdoutBuffer += typeof chunk === "string" ? chunk : new TextDecoder().decode(chunk);
			return true;
		});

		spyOn(process.stderr, "write").mockImplementation((chunk: string | Uint8Array) => {
			this.stderrBuffer += typeof chunk === "string" ? chunk : new TextDecoder().decode(chunk);
			return true;
		});
	}

	/**
	 * Set an environment variable, saving the original value.
	 * @internal
	 */
	private setEnvVar(key: string, value: string): void {
		if (!this.savedEnv.has(key)) {
			this.savedEnv.set(key, process.env[key]);
		}
		process.env[key] = value;
		Bun.env[key] = value;
	}

	/**
	 * Build the full hook input object with defaults.
	 * @internal
	 */
	private buildHookInput(hookType: string): Record<string, unknown> {
		const base = {
			session_id: crypto.randomUUID(),
			transcript_path: "/tmp/transcript.json",
			cwd: "/test/project",
			permission_mode: "default" as const,
			hook_event_name: hookType,
		};

		return {
			...base,
			...this.state.hookInput,
		};
	}

	/**
	 * Resolve a handler from a hook definition.
	 * Supports inline functions and file paths.
	 * @internal
	 */
	// biome-ignore lint/suspicious/noExplicitAny: Hook definitions have varied shapes
	private async resolveHandler(hookDef: any): Promise<PipelineHandler<unknown, unknown, TOptions, TState> | null> {
		// Check for inline pipeline function
		if (typeof hookDef.pipeline === "function") {
			return hookDef.pipeline;
		}

		// Check for inline handler function (raw handler)
		if (typeof hookDef.handler === "function") {
			// Wrap raw handler in pipeline interface
			// Raw handlers call event.end() directly, so we need to adapt
			throw new Error(
				"Raw handlers (handler property) are not supported in runHook(). " +
					"Use pipeline handlers or test raw handlers separately.",
			);
		}

		// Check for file path
		if (typeof hookDef.pipeline === "string") {
			return this.importHandler(hookDef.pipeline);
		}

		if (typeof hookDef.handler === "string") {
			throw new Error(
				"Raw handler file paths (handler property) are not supported in runHook(). " +
					"Use pipeline handlers or test raw handlers separately.",
			);
		}

		return null;
	}

	/**
	 * Import a handler from a file path.
	 * @internal
	 */
	private async importHandler(filePath: string): Promise<PipelineHandler<unknown, unknown, TOptions, TState>> {
		// Try to resolve the path
		let resolvedPath = filePath;

		// If it's a relative path, try to resolve from cwd
		if (filePath.startsWith("./") || filePath.startsWith("../")) {
			const cwd = process.cwd();
			resolvedPath = `${cwd}/${filePath}`;
		}

		try {
			// Dynamic import
			const module = await import(resolvedPath);
			const handler = module.default || module;

			if (typeof handler !== "function") {
				throw new Error(`Handler file "${filePath}" does not export a function`);
			}

			return handler;
		} catch (error) {
			if (error instanceof Error && error.message.includes("Cannot find module")) {
				throw new Error(
					`Could not import handler from "${filePath}". ` +
						`Make sure the file exists and the path is correct relative to cwd (${process.cwd()}).`,
				);
			}
			throw error;
		}
	}

	/**
	 * Build the handler context from configured state.
	 * @internal
	 */
	private buildHandlerContext(input: Record<string, unknown>): {
		input: unknown;
		options: TOptions;
		state: PluginState<TState>;
	} {
		// Create base state
		const baseState: BaseState = {
			projectDir: Bun.env.CLAUDE_PROJECT_DIR ?? "/test/project",
			pluginDir: Bun.env.CLAUDE_PLUGIN_ROOT ?? "/test/plugin",
			pluginEnvFile: Bun.env.CLAUDE_ENV_FILE ?? "/tmp/test-env.sh",
			// Provide no-op logger methods for testing
			log: () => {},
			info: () => {},
			debug: () => {},
		};

		// Merge base state with user-provided state
		const pluginState: PluginState<TState> = {
			...baseState,
			...(this.state.state as TState),
		};

		return {
			input,
			options: this.state.options as TOptions,
			state: pluginState,
		};
	}

	/**
	 * Build a HookTestResult from pipeline output.
	 * @internal
	 */
	private buildHookResultFromOutput(output: unknown): HookTestResult {
		// Check if it's a valid pipeline output
		if (!isPipelineOutput(output)) {
			return {
				exitCode: 1,
				stdout: "",
				stderr: "Handler returned non-pipeline output",
				output: typeof output === "object" && output !== null ? (output as Record<string, unknown>) : {},
				action: undefined,
				context: undefined,
				reason: "Handler returned non-pipeline output",
			};
		}

		const pipelineOutput = output as AnyPipelineOutput;

		// Extract convenience fields
		let action: HookAction | undefined;
		if ("action" in pipelineOutput) {
			action = pipelineOutput.action;
		}

		let context: string | undefined;
		if ("claudeContext" in pipelineOutput && pipelineOutput.claudeContext) {
			context = pipelineOutput.claudeContext;
		}

		let reason: string | undefined;
		if ("reason" in pipelineOutput && pipelineOutput.reason) {
			reason = pipelineOutput.reason;
		}

		// Determine exit code based on status
		const exitCode = pipelineOutput.status === "error" || pipelineOutput.status === "timeout" ? 1 : 0;

		return {
			exitCode,
			stdout: JSON.stringify(pipelineOutput),
			stderr: this.stderrBuffer,
			output: pipelineOutput as Record<string, unknown>,
			action,
			context,
			reason,
		};
	}

	// =========================================================================
	// COMMAND HELPERS
	// =========================================================================

	/**
	 * Resolve a command handler from a command definition.
	 * Supports inline functions and file paths.
	 * @internal
	 */
	private async resolveCommandHandler(
		commandDef: CommandDefinition,
	): Promise<CommandHandler<unknown, TOptions, TState> | null> {
		// Check for inline pipeline function
		if (typeof commandDef.pipeline === "function") {
			return commandDef.pipeline as CommandHandler<unknown, TOptions, TState>;
		}

		// Check for file path
		if (typeof commandDef.pipeline === "string") {
			return this.importCommandHandler(commandDef.pipeline);
		}

		return null;
	}

	/**
	 * Import a command handler from a file path.
	 * @internal
	 */
	private async importCommandHandler(filePath: string): Promise<CommandHandler<unknown, TOptions, TState>> {
		// Try to resolve the path
		let resolvedPath = filePath;

		// If it's a relative path, try to resolve from cwd
		if (filePath.startsWith("./") || filePath.startsWith("../")) {
			const cwd = process.cwd();
			resolvedPath = `${cwd}/${filePath}`;
		}

		try {
			// Dynamic import
			const module = await import(resolvedPath);
			const handler = module.default || module;

			if (typeof handler !== "function") {
				throw new Error(`Command handler file "${filePath}" does not export a function`);
			}

			return handler;
		} catch (error) {
			if (error instanceof Error && error.message.includes("Cannot find module")) {
				throw new Error(
					`Could not import command handler from "${filePath}". ` +
						`Make sure the file exists and the path is correct relative to cwd (${process.cwd()}).`,
				);
			}
			throw error;
		}
	}

	/**
	 * Validate command arguments against the command's schema.
	 * @internal
	 */
	private async validateCommandArgs(commandDef: CommandDefinition, args: Record<string, unknown>): Promise<unknown> {
		const schema = commandDef.args;

		// If no schema defined, return args as-is (empty object for no-arg commands)
		if (!schema) {
			return args;
		}

		// Cast to z.ZodType for proper method access
		const zodSchema = schema as z.ZodType<unknown>;

		// Use safeParseAsync for async validation
		const result = await zodSchema.safeParseAsync(args);

		if (!result.success) {
			const issues = result.error.issues
				// biome-ignore lint/suspicious/noExplicitAny: Zod issue type varies between versions
				.map((issue: any) => `${(issue.path || []).join(".")}: ${issue.message}`)
				.join(", ");
			throw new Error(`Argument validation failed: ${issues}`);
		}

		return result.data;
	}

	/**
	 * Build the command context from configured state and args.
	 * @internal
	 */
	private buildCommandContext(args: unknown): {
		args: unknown;
		options: TOptions;
		state: PluginState<TState>;
	} {
		// Create base state
		const baseState: BaseState = {
			projectDir: Bun.env.CLAUDE_PROJECT_DIR ?? "/test/project",
			pluginDir: Bun.env.CLAUDE_PLUGIN_ROOT ?? "/test/plugin",
			pluginEnvFile: Bun.env.CLAUDE_ENV_FILE ?? "/tmp/test-env.sh",
			// Provide no-op logger methods for testing
			log: () => {},
			info: () => {},
			debug: () => {},
		};

		// Merge base state with user-provided state
		const pluginState: PluginState<TState> = {
			...baseState,
			...(this.state.state as TState),
		};

		return {
			args,
			options: this.state.options as TOptions,
			state: pluginState,
		};
	}

	/**
	 * Validate command output structure.
	 * @internal
	 */
	private validateCommandOutput(output: CommandOutput, commandName: string): void {
		if (typeof output.exitCode !== "number") {
			throw new Error(`Command "${commandName}" returned invalid exitCode: ${output.exitCode}`);
		}
		if (typeof output.output !== "string") {
			throw new Error(`Command "${commandName}" returned invalid output: expected string`);
		}
		if (output.exitCode < 0 || output.exitCode > 255) {
			throw new Error(`Command "${commandName}" returned invalid exitCode: must be 0-255`);
		}
	}
}

// =============================================================================
// FACTORY FUNCTION
// =============================================================================

/**
 * Create a test builder for a plugin configuration.
 *
 * @remarks
 * This is typically called via `plugin.test()` rather than directly.
 *
 * @param config - Plugin configuration
 * @returns A new PluginTester instance
 *
 * @internal
 */
export function createTestBuilder<
	TOptions,
	TState,
	THooks extends Record<string, unknown[]>,
	TCommands extends Record<string, CommandDefinition>,
>(
	// biome-ignore lint/suspicious/noExplicitAny: Accept any plugin config
	config: PluginConfig<any, any, any>,
): PluginTester<TOptions, TState, THooks, TCommands> {
	return new PluginTester(config);
}
