/**
 * Fluent test builder for Claude Code plugins.
 *
 * @remarks
 * `PluginTestBuilder` provides a type-safe, fluent API for testing plugin hooks
 * and commands. It integrates with `ClaudeBinaryPlugin` to provide full type
 * inference for options, state, and hook inputs.
 *
 * @example
 * ```typescript
 * import myPlugin from "../plugin.js";
 *
 * describe("security hook", () => {
 *   let ctx: ReturnType<typeof myPlugin.test>;
 *
 *   beforeEach(() => {
 *     ctx = myPlugin.test()
 *       .withOptions({ DEBUG: false, API_KEY: "test" })
 *       .withState({ packageManager: "bun", gitRepo: true });
 *   });
 *
 *   afterEach(() => ctx.dispose());
 *
 *   test("blocks dangerous commands", async () => {
 *     const result = await ctx
 *       .withPreToolUseInput({
 *         tool_name: "Bash",
 *         tool_input: { command: "rm -rf /" },
 *       })
 *       .runHook("PreToolUse", "security");
 *
 *     expect(result.action).toBe("deny");
 *   });
 * });
 * ```
 *
 * @module
 */

import { mock, spyOn } from "bun:test";
import type { z } from "zod";
import type { ShellResult } from "../build/builder.js";
import type { CommandDefinition, PluginConfig } from "../pipeline/config.js";
import type { HookAction } from "../pipeline/types.js";
import { MockExitError } from "./mocks.js";

// =============================================================================
// HOOK INPUT TYPES
// =============================================================================

/**
 * Base fields present in all hook events.
 * These are auto-generated by the test builder.
 * @public
 */
export interface HookInputBase {
	session_id?: string;
	transcript_path?: string;
	cwd?: string;
	permission_mode?: "default" | "plan" | "acceptEdits" | "bypassPermissions";
}

/**
 * Input fields specific to PreToolUse hooks.
 * @public
 */
export interface PreToolUseInput extends HookInputBase {
	tool_name: string;
	tool_input: Record<string, unknown>;
	tool_use_id?: string;
}

/**
 * Input fields specific to PostToolUse hooks.
 * @public
 */
export interface PostToolUseInput extends HookInputBase {
	tool_name: string;
	tool_input: Record<string, unknown>;
	tool_response: Record<string, unknown>;
	tool_use_id?: string;
}

/**
 * Input fields specific to SessionStart hooks.
 * @public
 */
export interface SessionStartInput extends HookInputBase {
	source: "startup" | "resume" | "clear" | "compact";
}

/**
 * Input fields specific to SessionEnd hooks.
 * @public
 */
export interface SessionEndInput extends HookInputBase {
	reason: "clear" | "logout" | "prompt_input_exit" | "other";
}

/**
 * Input fields specific to Stop hooks.
 * @public
 */
export interface StopInput extends HookInputBase {
	stop_hook_active: boolean;
}

/**
 * Input fields specific to SubagentStop hooks.
 * @public
 */
export interface SubagentStopInput extends HookInputBase {
	stop_hook_active: boolean;
}

/**
 * Input fields specific to UserPromptSubmit hooks.
 * @public
 */
export interface UserPromptSubmitInput extends HookInputBase {
	prompt: string;
}

/**
 * Input fields specific to PreCompact hooks.
 * @public
 */
export interface PreCompactInput extends HookInputBase {
	trigger: "manual" | "auto";
	custom_instructions?: string;
}

/**
 * Input fields specific to Notification hooks.
 * @public
 */
export interface NotificationInput extends HookInputBase {
	message: string;
	notification_type: string;
}

/**
 * Input fields specific to PermissionRequest hooks.
 * @public
 */
export interface PermissionRequestInput extends HookInputBase {
	message: string;
	notification_type: string;
}

// =============================================================================
// RESULT TYPES
// =============================================================================

/**
 * Result from running a hook test.
 * @public
 */
export interface HookTestResult {
	/** Exit code from the hook (0 = success) */
	exitCode: number;
	/** Raw stdout output */
	stdout: string;
	/** Raw stderr output */
	stderr: string;
	/** Parsed JSON response from the hook */
	output: Record<string, unknown>;
	/** Convenience accessor for hook action (allow/deny/block/etc) */
	action?: HookAction;
	/** Convenience accessor for additionalContext */
	context?: string;
	/** Convenience accessor for reason */
	reason?: string;
}

/**
 * Result from running a command test.
 * @public
 */
export interface CommandTestResult {
	/** Exit code from the command */
	exitCode: number;
	/** Raw stdout output */
	stdout: string;
	/** Raw stderr output */
	stderr: string;
	/** Captured console.log calls */
	logs: string[];
	/** Captured console.error calls */
	errors: string[];
}

// =============================================================================
// BUILDER CONFIGURATION
// =============================================================================

/**
 * Internal state for the test builder.
 * @internal
 */
interface BuilderState<TOptions, TState> {
	options?: TOptions;
	state?: TState;
	hookInput?: Record<string, unknown>;
	hookEventName?: string;
	shellResponses: Map<string, ShellResult>;
	envVars: Map<string, string>;
}

// =============================================================================
// PLUGIN TEST BUILDER
// =============================================================================

/**
 * Fluent test builder for plugin hooks and commands.
 *
 * @typeParam TOptions - Validated options type from plugin schema
 * @typeParam TState - State type from setup function
 * @typeParam THooks - Hook definitions from plugin config
 * @typeParam TCommands - Command definitions from plugin config
 *
 * @public
 */
export class PluginTestBuilder<
	TOptions,
	TState,
	// biome-ignore lint/suspicious/noExplicitAny: Hooks map has optional properties that don't satisfy Record constraint
	THooks extends Record<string, any>,
	TCommands extends Record<string, CommandDefinition>,
> {
	private state: BuilderState<TOptions, TState> = {
		shellResponses: new Map(),
		envVars: new Map(),
	};

	private savedEnv: Map<string, string | undefined> = new Map();
	private stdoutBuffer = "";
	private stderrBuffer = "";
	private isDisposed = false;

	/**
	 * Plugin configuration reference for type inference.
	 * @internal
	 */
	// biome-ignore lint/suspicious/noExplicitAny: Store plugin config for reference
	private readonly pluginConfig: PluginConfig<any, any, any>;

	/**
	 * Create a new test builder for a plugin.
	 * @internal - Use `plugin.test()` instead
	 */
	// biome-ignore lint/suspicious/noExplicitAny: Accept any plugin config
	constructor(pluginConfig: PluginConfig<any, any, any>) {
		this.pluginConfig = pluginConfig;
	}

	// =========================================================================
	// CONFIGURATION METHODS (Fluent)
	// =========================================================================

	/**
	 * Set the plugin options for this test.
	 *
	 * @param options - Full options object matching the plugin schema
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * ctx.withOptions({ DEBUG: true, API_KEY: "test-key" });
	 * ```
	 */
	withOptions(options: TOptions): this {
		this.state.options = options;
		return this;
	}

	/**
	 * Set the plugin state (from setup function) for this test.
	 *
	 * @param state - Full state object matching setup() return type
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * ctx.withState({ packageManager: "bun", gitRepo: true, projectRoot: "/test" });
	 * ```
	 */
	withState(state: TState): this {
		this.state.state = state;
		return this;
	}

	// =========================================================================
	// HOOK INPUT METHODS (Fluent, type-aware)
	// =========================================================================

	/**
	 * Set input for a PreToolUse hook test.
	 *
	 * @param input - PreToolUse-specific input fields
	 * @returns this for chaining
	 */
	withPreToolUseInput(input: PreToolUseInput): this {
		this.state.hookEventName = "PreToolUse";
		this.state.hookInput = {
			hook_event_name: "PreToolUse",
			tool_use_id: input.tool_use_id ?? `tool-${crypto.randomUUID()}`,
			...input,
		};
		return this;
	}

	/**
	 * Set input for a PostToolUse hook test.
	 *
	 * @param input - PostToolUse-specific input fields
	 * @returns this for chaining
	 */
	withPostToolUseInput(input: PostToolUseInput): this {
		this.state.hookEventName = "PostToolUse";
		this.state.hookInput = {
			hook_event_name: "PostToolUse",
			tool_use_id: input.tool_use_id ?? `tool-${crypto.randomUUID()}`,
			...input,
		};
		return this;
	}

	/**
	 * Set input for a SessionStart hook test.
	 *
	 * @param input - SessionStart-specific input fields
	 * @returns this for chaining
	 */
	withSessionStartInput(input: SessionStartInput): this {
		this.state.hookEventName = "SessionStart";
		this.state.hookInput = {
			hook_event_name: "SessionStart",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a SessionEnd hook test.
	 *
	 * @param input - SessionEnd-specific input fields
	 * @returns this for chaining
	 */
	withSessionEndInput(input: SessionEndInput): this {
		this.state.hookEventName = "SessionEnd";
		this.state.hookInput = {
			hook_event_name: "SessionEnd",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a Stop hook test.
	 *
	 * @param input - Stop-specific input fields
	 * @returns this for chaining
	 */
	withStopInput(input: StopInput): this {
		this.state.hookEventName = "Stop";
		this.state.hookInput = {
			hook_event_name: "Stop",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a SubagentStop hook test.
	 *
	 * @param input - SubagentStop-specific input fields
	 * @returns this for chaining
	 */
	withSubagentStopInput(input: SubagentStopInput): this {
		this.state.hookEventName = "SubagentStop";
		this.state.hookInput = {
			hook_event_name: "SubagentStop",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a UserPromptSubmit hook test.
	 *
	 * @param input - UserPromptSubmit-specific input fields
	 * @returns this for chaining
	 */
	withUserPromptSubmitInput(input: UserPromptSubmitInput): this {
		this.state.hookEventName = "UserPromptSubmit";
		this.state.hookInput = {
			hook_event_name: "UserPromptSubmit",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a PreCompact hook test.
	 *
	 * @param input - PreCompact-specific input fields
	 * @returns this for chaining
	 */
	withPreCompactInput(input: PreCompactInput): this {
		this.state.hookEventName = "PreCompact";
		this.state.hookInput = {
			hook_event_name: "PreCompact",
			custom_instructions: input.custom_instructions ?? "",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a Notification hook test.
	 *
	 * @param input - Notification-specific input fields
	 * @returns this for chaining
	 */
	withNotificationInput(input: NotificationInput): this {
		this.state.hookEventName = "Notification";
		this.state.hookInput = {
			hook_event_name: "Notification",
			...input,
		};
		return this;
	}

	/**
	 * Set input for a PermissionRequest hook test.
	 *
	 * @param input - PermissionRequest-specific input fields
	 * @returns this for chaining
	 */
	withPermissionRequestInput(input: PermissionRequestInput): this {
		this.state.hookEventName = "PermissionRequest";
		this.state.hookInput = {
			hook_event_name: "PermissionRequest",
			...input,
		};
		return this;
	}

	// =========================================================================
	// SHELL MOCKING (Fluent)
	// =========================================================================

	/**
	 * Add a mock shell response for a command pattern.
	 *
	 * @param pattern - Command string or pattern to match
	 * @param result - ShellResult to return for matching commands
	 * @returns this for chaining
	 *
	 * @example
	 * ```typescript
	 * ctx.withShell("git status", { exitCode: 0, stdout: "clean", stderr: "" });
	 * ```
	 */
	withShell(pattern: string, result: ShellResult): this {
		this.state.shellResponses.set(pattern, result);
		return this;
	}

	// =========================================================================
	// EXECUTION METHODS (Terminal operations)
	// =========================================================================

	/**
	 * Run a hook handler with the configured test context.
	 *
	 * @param hookType - The hook event type (e.g., "PreToolUse")
	 * @param hookName - The specific hook name to run
	 * @returns Promise resolving to the hook test result
	 *
	 * @example
	 * ```typescript
	 * const result = await ctx.runHook("PreToolUse", "security");
	 * expect(result.action).toBe("allow");
	 * ```
	 */
	async runHook<K extends keyof THooks>(hookType: K, _hookName: string): Promise<HookTestResult> {
		this.validateState();
		this.setupMocks();

		let exitCode = 0;

		try {
			// Import and run the hook dynamically
			// For now, we'll create a mock handler context
			// The actual implementation will integrate with the pipeline runtime
			const hookInput = this.buildHookInput(hookType as string);

			// Mock stdin with the hook input
			spyOn(Bun.stdin, "text").mockResolvedValue(JSON.stringify(hookInput));

			// Mock process.exit
			const originalExit = process.exit;
			process.exit = mock((code?: number) => {
				exitCode = code ?? 0;
				throw new MockExitError(code ?? 0);
			}) as typeof process.exit;

			try {
				// The hook would be run here - for now we simulate
				// In the full implementation, this would call the actual hook handler
				// through the pipeline runtime
				throw new MockExitError(0); // Simulate successful exit
			} catch (error) {
				if (!(error instanceof MockExitError)) {
					process.exit = originalExit;
					throw error;
				}
			} finally {
				process.exit = originalExit;
			}
		} finally {
			// Don't restore mocks here - dispose() handles that
		}

		return this.buildHookResult(exitCode);
	}

	/**
	 * Run a command handler with the configured test context.
	 *
	 * @param command - The command name to run
	 * @param args - Optional command arguments
	 * @returns Promise resolving to the command test result
	 *
	 * @example
	 * ```typescript
	 * const result = await ctx.runCommand("lint", { fix: true });
	 * expect(result.exitCode).toBe(0);
	 * ```
	 */
	async runCommand<K extends keyof TCommands>(
		_command: K,
		_args?: TCommands[K] extends CommandDefinition ? z.infer<TCommands[K]["args"]> : never,
	): Promise<CommandTestResult> {
		this.validateState();
		this.setupMocks();

		const logs: string[] = [];
		const errors: string[] = [];
		let exitCode = 0;

		const originalLog = console.log;
		const originalError = console.error;
		const originalExit = process.exit;

		console.log = mock((...args: unknown[]) => {
			logs.push(args.map(String).join(" "));
		}) as typeof console.log;

		console.error = mock((...args: unknown[]) => {
			errors.push(args.map(String).join(" "));
		}) as typeof console.error;

		process.exit = mock((code?: number) => {
			exitCode = code ?? 0;
			throw new MockExitError(code ?? 0);
		}) as typeof process.exit;

		try {
			// The command would be run here
			// In the full implementation, this would call the actual command handler
			throw new MockExitError(0); // Simulate successful exit
		} catch (error) {
			if (!(error instanceof MockExitError)) {
				throw error;
			}
		} finally {
			console.log = originalLog;
			console.error = originalError;
			process.exit = originalExit;
		}

		return {
			exitCode,
			stdout: this.stdoutBuffer,
			stderr: this.stderrBuffer,
			logs,
			errors,
		};
	}

	// =========================================================================
	// CLEANUP
	// =========================================================================

	/**
	 * Clean up all mocks and restore original state.
	 * Call this in afterEach() to prevent test pollution.
	 *
	 * @example
	 * ```typescript
	 * afterEach(() => ctx.dispose());
	 * ```
	 */
	dispose(): void {
		if (this.isDisposed) return;
		this.isDisposed = true;

		// Restore environment variables
		for (const [key, value] of this.savedEnv) {
			if (value === undefined) {
				delete process.env[key];
				delete Bun.env[key];
			} else {
				process.env[key] = value;
				Bun.env[key] = value;
			}
		}

		// Reset IO mocks
		// @ts-expect-error - accessing mock restore
		if (Bun.stdin.text?.mockRestore) {
			// @ts-expect-error - accessing mock restore
			Bun.stdin.text.mockRestore();
		}
		// @ts-expect-error - accessing mock restore
		if (process.stdout.write?.mockRestore) {
			// @ts-expect-error - accessing mock restore
			process.stdout.write.mockRestore();
		}
		// @ts-expect-error - accessing mock restore
		if (process.stderr.write?.mockRestore) {
			// @ts-expect-error - accessing mock restore
			process.stderr.write.mockRestore();
		}

		// Clear state
		this.state = {
			shellResponses: new Map(),
			envVars: new Map(),
		};
		this.savedEnv.clear();
		this.stdoutBuffer = "";
		this.stderrBuffer = "";
	}

	// =========================================================================
	// INTERNAL HELPERS
	// =========================================================================

	/**
	 * Validate that required state has been configured.
	 * @internal
	 */
	private validateState(): void {
		if (!this.state.options) {
			throw new Error("PluginTestBuilder: withOptions() must be called before running tests");
		}
		if (!this.state.state) {
			throw new Error("PluginTestBuilder: withState() must be called before running tests");
		}
	}

	/**
	 * Set up mocks for the test run.
	 * @internal
	 */
	private setupMocks(): void {
		// Save and set environment variables
		const prefix = this.pluginConfig.prefix;

		// Set up base env vars
		this.setEnvVar("CLAUDE_SESSION_ID", crypto.randomUUID());
		this.setEnvVar("CLAUDE_PROJECT_DIR", "/test/project");
		this.setEnvVar("CLAUDE_PLUGIN_ROOT", "/test/plugin");
		this.setEnvVar("CLAUDE_ENV_FILE", "/tmp/test-env.sh");

		// Set up options as env vars
		if (this.state.options) {
			for (const [key, value] of Object.entries(this.state.options as Record<string, unknown>)) {
				const envKey = `${prefix}_${key}`;
				this.setEnvVar(envKey, String(value));
			}
		}

		// Set up state as encoded env var
		if (this.state.state) {
			const stateJson = JSON.stringify(this.state.state);
			const stateBase64 = Buffer.from(stateJson).toString("base64");
			this.setEnvVar(`${prefix}_PLUGIN_STATE`, stateBase64);
		}

		// Mock stdout/stderr capture
		spyOn(process.stdout, "write").mockImplementation((chunk: string | Uint8Array) => {
			this.stdoutBuffer += typeof chunk === "string" ? chunk : new TextDecoder().decode(chunk);
			return true;
		});

		spyOn(process.stderr, "write").mockImplementation((chunk: string | Uint8Array) => {
			this.stderrBuffer += typeof chunk === "string" ? chunk : new TextDecoder().decode(chunk);
			return true;
		});
	}

	/**
	 * Set an environment variable, saving the original value.
	 * @internal
	 */
	private setEnvVar(key: string, value: string): void {
		if (!this.savedEnv.has(key)) {
			this.savedEnv.set(key, process.env[key]);
		}
		process.env[key] = value;
		Bun.env[key] = value;
	}

	/**
	 * Build the full hook input object with defaults.
	 * @internal
	 */
	private buildHookInput(hookType: string): Record<string, unknown> {
		const base = {
			session_id: crypto.randomUUID(),
			transcript_path: "/tmp/transcript.json",
			cwd: "/test/project",
			permission_mode: "default" as const,
			hook_event_name: hookType,
		};

		return {
			...base,
			...this.state.hookInput,
		};
	}

	/**
	 * Build the hook test result from captured output.
	 * @internal
	 */
	private buildHookResult(exitCode: number): HookTestResult {
		let output: Record<string, unknown> = {};
		let action: HookAction | undefined;
		let context: string | undefined;
		let reason: string | undefined;

		try {
			if (this.stdoutBuffer) {
				output = JSON.parse(this.stdoutBuffer);

				// Extract convenience fields
				const hookOutput = output.hookSpecificOutput as Record<string, unknown> | undefined;
				if (hookOutput) {
					if (hookOutput.permissionDecision) {
						action = hookOutput.permissionDecision as HookAction;
					}
					if (hookOutput.decision) {
						action = hookOutput.decision as HookAction;
					}
					if (hookOutput.additionalContext) {
						context = hookOutput.additionalContext as string;
					}
					if (hookOutput.reason) {
						reason = hookOutput.reason as string;
					}
				}
			}
		} catch {
			// Output wasn't valid JSON
		}

		return {
			exitCode,
			stdout: this.stdoutBuffer,
			stderr: this.stderrBuffer,
			output,
			action,
			context,
			reason,
		};
	}
}

// =============================================================================
// FACTORY FUNCTION
// =============================================================================

/**
 * Create a test builder for a plugin configuration.
 *
 * @remarks
 * This is typically called via `plugin.test()` rather than directly.
 *
 * @param config - Plugin configuration
 * @returns A new PluginTestBuilder instance
 *
 * @internal
 */
export function createTestBuilder<
	TOptions,
	TState,
	THooks extends Record<string, unknown[]>,
	TCommands extends Record<string, CommandDefinition>,
>(
	// biome-ignore lint/suspicious/noExplicitAny: Accept any plugin config
	config: PluginConfig<any, any, any>,
): PluginTestBuilder<TOptions, TState, THooks, TCommands> {
	return new PluginTestBuilder(config);
}
