import { Schema } from "effect";
import type { NoAction } from "../outcomes/NoAction.js";
import type { HookDefinition, PluginHandler } from "../plugin/handler.js";
import { NormalizedPathSchema, SessionIdSchema, TranscriptPathSchema, normalizePath } from "../schemas/branded.js";
import { HookPermissionsModeSchema, PreCompactTriggerSchema } from "../schemas/hook-literals.js";
import { PassthroughOutputSchema, PassthroughResponse, toPassthroughResponse } from "./shared.js";

// =============================================================================
// 1. INPUT SCHEMA — raw wire format from stdin
// =============================================================================

/**
 * Input schema for PostCompact wire format from Claude Code stdin.
 * @public
 */
export class PostCompactInput extends Schema.Class<PostCompactInput>("PostCompactInput")({
	/** Unique identifier for the current session (UUID format) */
	session_id: SessionIdSchema,
	/** Absolute path to the conversation transcript JSON file (optional) */
	transcript_path: Schema.optional(TranscriptPathSchema),
	/** Current working directory (optional) */
	cwd: Schema.optional(Schema.String),
	/** Current permission mode (optional) */
	permission_mode: Schema.optional(HookPermissionsModeSchema),
	/** The type of hook event */
	hook_event_name: Schema.Literal("PostCompact"),
	/** Unique identifier for the subagent (present when hook fires inside a subagent) */
	agent_id: Schema.optional(Schema.String),
	/** Agent name (present when session uses --agent or hook fires inside a subagent) */
	agent_type: Schema.optional(Schema.String),
	/** What triggered the compact operation */
	trigger: PreCompactTriggerSchema,
	/** The conversation summary generated by the compact operation */
	compact_summary: Schema.String,
}) {}

// =============================================================================
// 2. EVENT CLASS — domain model (what handlers receive)
// =============================================================================

/**
 * Schema.Class for PostCompact events.
 * @public
 */
export class PostCompactEvent extends Schema.Class<PostCompactEvent>("PostCompactEvent")({
	/** Unique identifier for the current session (UUID format) */
	session_id: SessionIdSchema,
	/** Absolute path to the conversation transcript JSON file (optional) */
	transcript_path: Schema.optional(NormalizedPathSchema),
	/** Current working directory (optional) */
	cwd: Schema.optional(NormalizedPathSchema),
	/** Current permission mode (optional) */
	permission_mode: Schema.optional(HookPermissionsModeSchema),
	/** The type of hook event */
	hook_event_name: Schema.Literal("PostCompact"),
	/** Unique identifier for the subagent (present when hook fires inside a subagent) */
	agent_id: Schema.optional(Schema.String),
	/** Agent name (present when session uses --agent or hook fires inside a subagent) */
	agent_type: Schema.optional(Schema.String),
	/** What triggered the compact operation */
	trigger: PreCompactTriggerSchema,
	/** The conversation summary generated by the compact operation */
	compact_summary: Schema.String,
}) {
	static fromInput(input: PostCompactInput): PostCompactEvent {
		return new PostCompactEvent({
			session_id: input.session_id,
			permission_mode: input.permission_mode,
			hook_event_name: input.hook_event_name,
			agent_id: input.agent_id,
			agent_type: input.agent_type,
			trigger: input.trigger,
			compact_summary: input.compact_summary,
			cwd: input.cwd ? normalizePath(input.cwd) : undefined,
			transcript_path: input.transcript_path ? normalizePath(input.transcript_path) : undefined,
		});
	}
}

// =============================================================================
// 3. OUTCOME UNION
// =============================================================================

/**
 * Valid outcome types for PostCompact handlers.
 * @public
 */
export type PostCompactOutcome = NoAction;

/**
 * Set of valid outcome tags for PostCompact hooks.
 * @public
 */
export const VALID_OUTCOME_TAGS = new Set(["NoAction"]);

// =============================================================================
// 4. OUTPUT SCHEMA — passthrough (no response data)
// =============================================================================

/** @public */
export const PostCompactOutputSchema = PassthroughOutputSchema;

/** @public */
export type PostCompactOutput = typeof PostCompactOutputSchema.Type;

// =============================================================================
// 5. RESPONSE SCHEMA — passthrough (empty object)
// =============================================================================

export { PassthroughResponse as PostCompactResponse, toPassthroughResponse as toPostCompactResponse };

// =============================================================================
// 6. HANDLER TYPE
// =============================================================================

/**
 * Handler function type for PostCompact hooks.
 * @public
 */
export type PostCompactHandler<TOptions, TState = Record<string, unknown>> = PluginHandler<
	PostCompactInput,
	PostCompactOutput,
	TOptions,
	TState,
	PostCompactOutcome
>;

// =============================================================================
// 7. HOOK DEFINITION TYPE
// =============================================================================

/**
 * Hook definition type for PostCompact hooks.
 * @public
 */
export type PostCompactHookDefinition<TOptions, TState = Record<string, unknown>> = HookDefinition<
	PostCompactInput,
	PostCompactOutput,
	unknown,
	TOptions,
	TState,
	PostCompactOutcome
>;
